### PR TITLE
Release: v2024.8.2-rc.2

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/db-client-go 99d096fbd19cbf545111a5de5c9779ba6aa3966f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 26dca4618c3a8db593e209e048e84bfd38b3a928

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore-restic-plugin 1a8b875a2f8f73cea1a6cbac5ee04ae64a065a87

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-csi-snapshotter-plugin 1b66901dd3c911f8efbcffbef23ebb374923e9bf

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-restic-plugin 9edee3a8fd9ecff2ce9100326282bce37ba94ed7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-archiver a54178b969b655f263d933747bdaee01e3969ead

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-archiver 0949ab0cbd241de7bff7e8dad242e68eac3abb1e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-restic-plugin 4c643343588e14bc0d72e214cdf60b4e2cdf696a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator 3a92ab8163830d46bb6fdf8bbaa9b5492a30553e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mssql-coordinator b6e43327aabd8cbf868bd4e586cc16bd5b4449b2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator b43e1a42906584118d768adfb2da6c2c1cebf8a8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/crd-manager 6a17ac75557b1be0d11c0dccd7bd0bacf1d195ce

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kubedb-manifest-plugin 8b1207d979b1ad47344492e8573ecb6b85af2bf4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 4db202b76118b3982f522289e49ebd4c60a53425

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-csi-snapshotter-plugin 5fd0cf8c222c5ba1b99278153fe5e035583868c8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/zookeeper 1051b1db518f3896d29b17beb120849ea5382086

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 2f717399eddd3ff02460f3498248199a9836a479

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 25b10bb6e103336e759a4114415ae55aad168ec8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests b279ee9f1550af3207f61f0cac2bb65144780c12

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 92a607fa54b382f8f669bfa0dedf341897205a7d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/solr a75340641768a27d90a071a4592e30139162036e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka 98b8a40436f59a753d2650bda8a7fed955f2a40c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch-restic-plugin 2fabca1fd46fd080905ae1c3cb2e43cf951be961

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore-coordinator 33a157b1454a4899d2a0615b6382d03bd1ba7d0f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-restic-plugin e27dc68eaf6eb3c72d4787fbd218449d2a5c0b5c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/rabbitmq 6e8ac555fde690441d9280fe7807911461dcb935

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard-restic-plugin 6188e57b98f9f36a92b8ece7cf0c4e99434691ed

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb 86038a2012ead3776e44a9e6d03daee45dabbb22

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-csi-snapshotter-plugin 744dd4a1cb91d26851ac14c9e8e60116a284be6e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql b2cc7f236d7a91bd5f2fdab9d8171ca32e3bce55

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/clickhouse 352d87ca33c4b50340430021c808f900ce4dfd3e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 7e9c8648c0ccfc266d0f599b7e76a9669e184ef6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-csi-snapshotter-plugin 6df0b0f4cbbc887dd0f0fb0c5e7112408d542d1f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/zookeeper-restic-plugin 0f2644b97206578e27d82d832047d535d9f07e33

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-archiver 138bcf7cd74a810bd40bf26550568227e538eb4c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ferretdb 0a38354aa0e72b89e0a376b756297de4e6f634ed

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore 09de410f9a0a2284398848b5f4a6cc68b8f7119e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 77ca2092b3221e06257f58b71becc2fe1fceffa9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/druid af49e11220a9acda47771ebd36dac99b22eb8f9c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-restic-plugin 73a3ff8015ee7711ab94e573b898fd5385d9af31

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator 8c6d9de3a79a9f347b1ebc295e428f5b7222ea8d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-restic-plugin 15072a88c008052e2fa5eb25b258dadefc795a95

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator cbae32d458dfca8a690ca38b55263cda715f6c67

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch fd8abfca30081a136de257bbf3d0e1cc444f3e88

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/elasticsearch fd8abfca30081a136de257bbf3d0e1cc444f3e88

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached f2ab956b47db05c2f66d2425d82112b9a8278c8b
/go github.com/kubedb/memcached kubedb.dev/memcached 
/ready-to-tag github.com/kubedb/provider-aws 329ca2434cc87088566a985b034697eea15f584a
/go github.com/kubedb/provider-aws kubedb.dev/provider-aws 
/ready-to-tag github.com/kubedb/pgpool 7df31597fcd6fd50f10c472ffcb3b27826bddc0a
/go github.com/kubedb/pgpool kubedb.dev/pgpool 
/ready-to-tag github.com/kubedb/provider-gcp 61a45eb086d91d37b389dcd437856fa9de1dd4a2
/go github.com/kubedb/provider-gcp kubedb.dev/provider-gcp 
/ready-to-tag github.com/kubedb/mssqlserver 76b74614121b7930ef6e1df48d7f2f2a1dc36708
/go github.com/kubedb/mssqlserver kubedb.dev/mssqlserver 
/ready-to-tag github.com/kubedb/mysql-router-init f1f471e8689c159176d9b2673647581e1b0ba8a3
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/ready-to-tag github.com/kubedb/provider-azure 387e3f2720147ee7b0f48c2b71a4a7fcd0ada4e7
/go github.com/kubedb/provider-azure kubedb.dev/provider-azure 
/tagged github.com/kubedb/druid
/go github.com/kubedb/druid kubedb.dev/druid 
/tagged github.com/kubedb/mongodb-csi-snapshotter-plugin
/go github.com/kubedb/mongodb-csi-snapshotter-plugin kubedb.dev/mongodb-csi-snapshotter-plugin 
/tagged github.com/kubedb/postgres
/go github.com/kubedb/postgres kubedb.dev/postgres 
/tagged github.com/kubedb/rabbitmq
/go github.com/kubedb/rabbitmq kubedb.dev/rabbitmq 
/tagged github.com/kubedb/clickhouse
/go github.com/kubedb/clickhouse kubedb.dev/clickhouse 
/tagged github.com/kubedb/kubedb-manifest-plugin
/go github.com/kubedb/kubedb-manifest-plugin kubedb.dev/kubedb-manifest-plugin 
/tagged github.com/kubedb/percona-xtradb
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/tagged github.com/kubedb/postgres-csi-snapshotter-plugin
/go github.com/kubedb/postgres-csi-snapshotter-plugin kubedb.dev/postgres-csi-snapshotter-plugin 
/tagged github.com/kubedb/percona-xtradb-coordinator
/tagged github.com/kubedb/mongodb
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/tagged github.com/kubedb/redis-restic-plugin
/go github.com/kubedb/redis-restic-plugin kubedb.dev/redis-restic-plugin 
/tagged github.com/kubedb/singlestore-restic-plugin
/go github.com/kubedb/singlestore-restic-plugin kubedb.dev/singlestore-restic-plugin 
/tagged github.com/kubedb/mysql-csi-snapshotter-plugin
/tagged github.com/kubedb/postgres-archiver
/go github.com/kubedb/postgres-archiver kubedb.dev/postgres-archiver 
/tagged github.com/kubedb/mariadb
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/tagged github.com/kubedb/redis
/go github.com/kubedb/redis kubedb.dev/redis 
/tagged github.com/kubedb/replication-mode-detector
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/tagged github.com/kubedb/mariadb-restic-plugin
/go github.com/kubedb/mariadb-restic-plugin kubedb.dev/mariadb-restic-plugin 
/tagged github.com/kubedb/elasticsearch
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/tagged github.com/kubedb/tests
/go github.com/kubedb/tests kubedb.dev/tests 
/tagged github.com/kubedb/kafka
/go github.com/kubedb/kafka kubedb.dev/kafka 
/tagged github.com/kubedb/dashboard-restic-plugin
/tagged github.com/kubedb/zookeeper-restic-plugin
/go github.com/kubedb/zookeeper-restic-plugin kubedb.dev/zookeeper-restic-plugin 
/tagged github.com/kubedb/singlestore
/go github.com/kubedb/singlestore kubedb.dev/singlestore 
/tagged github.com/kubedb/mysql-coordinator
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/tagged github.com/kubedb/mongodb-restic-plugin
/go github.com/kubedb/mongodb-restic-plugin kubedb.dev/mongodb-restic-plugin 
/tagged github.com/kubedb/mysql-restic-plugin
/go github.com/kubedb/mysql-restic-plugin kubedb.dev/mysql-restic-plugin 
/tagged github.com/kubedb/elasticsearch-restic-plugin
/go github.com/kubedb/elasticsearch-restic-plugin kubedb.dev/elasticsearch-restic-plugin 
/tagged github.com/kubedb/mysql
/go github.com/kubedb/mysql kubedb.dev/mysql 
/tagged github.com/kubedb/mariadb-csi-snapshotter-plugin
/tagged github.com/kubedb/mariadb-archiver
/go github.com/kubedb/mariadb-archiver kubedb.dev/mariadb-archiver 
/tagged github.com/kubedb/pg-coordinator
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/tagged github.com/kubedb/cli
/go github.com/kubedb/cli kubedb.dev/cli 
/tagged github.com/kubedb/mssql-coordinator
/go github.com/kubedb/mssql-coordinator kubedb.dev/mssql-coordinator 
/tagged github.com/kubedb/singlestore-coordinator
/go github.com/kubedb/singlestore-coordinator kubedb.dev/singlestore-coordinator 
/tagged github.com/kubedb/zookeeper
/go github.com/kubedb/zookeeper kubedb.dev/zookeeper 
/tagged github.com/kubedb/mariadb-coordinator
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/tagged github.com/kubedb/postgres-restic-plugin
/go github.com/kubedb/postgres-restic-plugin kubedb.dev/postgres-restic-plugin 
/tagged github.com/kubedb/mysql-archiver
/go github.com/kubedb/mysql-archiver kubedb.dev/mysql-archiver 
/tagged github.com/kubedb/redis-coordinator
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/tagged github.com/kubedb/crd-manager
/tagged github.com/kubedb/solr
/go github.com/kubedb/solr kubedb.dev/solr 
/tagged github.com/kubedb/ferretdb
/go github.com/kubedb/ferretdb kubedb.dev/ferretdb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard b23df248b152d8e2e255276fbe7fc2f443bc529a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql c7df11cb2d1bbecdc41b91975a3bef0550399316

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer ff8c54915220aba3767267bc51035fbb7012ae01

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner f792d7a5a004fa2b8434fa3acffbdcb9e0bdf6ca

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 893dc3acbfa0ccfc8fa0183a9bcbbf17d24e26e4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 10ca56135c065538a6e49ea9251cbaf53aa56bbe

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 10ca56135c065538a6e49ea9251cbaf53aa56bbe
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/ready-to-tag github.com/kubedb/ui-server 893dc3acbfa0ccfc8fa0183a9bcbbf17d24e26e4
/go github.com/kubedb/ui-server kubedb.dev/ui-server 
/tagged github.com/kubedb/provisioner
/go github.com/kubedb/provisioner kubedb.dev/provisioner

**Comment by 1gtm** [comment]
/tagged github.com/kubedb/provisioner
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/tagged github.com/kubedb/ui-server
/go github.com/kubedb/ui-server kubedb.dev/ui-server 
/tagged github.com/kubedb/schema-manager
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager 2cfccf3ec23da1be3f622f8be67c2df087439f29

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler a03964eca08591f913136d03686f5f9231ad91b9

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/121
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server d45bc39555e04f8a9a1e72eb568e877f7037ecf8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 1466c9d52820d57878309bf5ddcdb7679fe0e6a2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs 38afc7c621cca4fd58a8dcbbcf4f44c48eb9dcba

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 64a8ffbf0acabe58ead2e09f9b8fabafb45e95ce

**Pull request merged**
