### PR TITLE
Release: v2023.11.29-rc.0

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/mysql/pull/572
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/kafka/pull/48
/go github.com/kubedb/kafka kubedb.dev/kafka 
/pr https://github.com/kubedb/mysql-coordinator/pull/89
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/pr https://github.com/kubedb/redis-coordinator/pull/80
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/pr https://github.com/kubedb/postgres-restic-plugin/pull/4
/go github.com/kubedb/postgres-restic-plugin kubedb.dev/postgres-restic-plugin 
/pr https://github.com/kubedb/kubedb-manifest-plugin/pull/28
/go github.com/kubedb/kubedb-manifest-plugin kubedb.dev/kubedb-manifest-plugin 
/pr https://github.com/kubedb/replication-mode-detector/pull/244
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/percona-xtradb-coordinator/pull/49
/go github.com/kubedb/percona-xtradb-coordinator kubedb.dev/percona-xtradb-coordinator 
/pr https://github.com/kubedb/pg-coordinator/pull/139
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/pr https://github.com/kubedb/percona-xtradb/pull/331
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/memcached/pull/405
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/redis-restic-plugin/pull/9
/go github.com/kubedb/redis-restic-plugin kubedb.dev/redis-restic-plugin 
/pr https://github.com/kubedb/tests/pull/270
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/cli/pull/737
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/elasticsearch/pull/678
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/elasticsearch-restic-plugin/pull/8
/go github.com/kubedb/elasticsearch-restic-plugin kubedb.dev/elasticsearch-restic-plugin 
/pr https://github.com/kubedb/mariadb/pull/233
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/pr https://github.com/kubedb/mariadb-archiver/pull/3
/go github.com/kubedb/mariadb-archiver kubedb.dev/mariadb-archiver 
/pr https://github.com/kubedb/mysql-restic-plugin/pull/11
/go github.com/kubedb/mysql-restic-plugin kubedb.dev/mysql-restic-plugin 
/pr https://github.com/kubedb/mongodb-csi-snapshotter-plugin/pull/3
/go github.com/kubedb/mongodb-csi-snapshotter-plugin kubedb.dev/mongodb-csi-snapshotter-plugin 
/pr https://github.com/kubedb/mariadb-coordinator/pull/92
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/ready-to-tag github.com/kubedb/postgres-archiver 1feeaebefd65db6dd6b41ad962a29fea9ccfb4e6
/go github.com/kubedb/postgres-archiver kubedb.dev/postgres-archiver 
/pr https://github.com/kubedb/mongodb-restic-plugin/pull/13
/go github.com/kubedb/mongodb-restic-plugin kubedb.dev/mongodb-restic-plugin 
/ready-to-tag github.com/kubedb/mysql-router-init 2a59ae128a85a9bf4058cbe73365d6f081e0c154
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/postgres-csi-snapshotter-plugin/pull/6
/go github.com/kubedb/postgres-csi-snapshotter-plugin kubedb.dev/postgres-csi-snapshotter-plugin 
/pr https://github.com/kubedb/postgres/pull/684
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/mongodb/pull/581
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/redis/pull/495
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/mysql-archiver/pull/2
/go github.com/kubedb/mysql-archiver kubedb.dev/mysql-archiver

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 3a4dcc478a86cf12f4804acb534aff4a6d8a5bfe

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 3c005b51aec496c251fa83fcbcb260f572227ca3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 6b2943f19b10174221ef1daaa82fba13d654a5b1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator 9f724e431d1b8a569ee1c718bf5257eeff88406d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 8738ad73e4bdcb75aea3f226f50d325bba9792d3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 77886a28a2252906c4af85336446d4ce066bc7b5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator e4efa4dbbc457a6859bb77b103d8adc1d315ad33

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached e44be0a68cac6b1f062092e630e387263b46d5a7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb d374a542a492c818bf0e059a174cfbe39710ac91

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-csi-snapshotter-plugin f06d3441821f40c62bcaef6494cd0231197fdfb1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-csi-snapshotter-plugin 02a45da639435058576598985c75e44669edefe5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator bf515bfaf70359f43697caaf0017b2f5807ee5c4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-restic-plugin 745f5cbc2dd41c67d674e7e94202e2d70eb0614b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-restic-plugin b255e47501f8a4e3d08c87037e8e3e1e342f80ae

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch-restic-plugin eb95c8464986e0eb1a26611fda3c559578cbb176

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-restic-plugin f8de18b5f4c5c814e6031d2560f5444068cdac16

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kubedb-manifest-plugin bef777cb97909995a021c8eed96cb51f5232a660

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-restic-plugin 8208814fe22002aa70e46168f2023aee2452d856

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 966f14caee50c7058d0c8960509e67591a2402fa

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb e360fd8270909d0f51ce55010e46f5804fed2326

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator b5e481fcfa3bb1f8a61fd3bd70d4f2b96a2e18d6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-archiver f79286abd146c9e0ebcdc9d81a4def0aae223337

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-archiver 65fd6bfb16532f2daa126e3a373dea7ac7f34050

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka 0770fff8e60bc5e80ce46c994fca1f5db22c71bc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests bfd1ec7982f34aa4d269ef64ea51957765fb7a26

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb c368ec94295af9d30d57af1f75b425f9451b2e68

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator 69e7d1e9c6684557b4ac2c370582f775020d76e2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 21ba9f0f9d7a9da29fcb594b0fbcc0064b27f1bc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql c4775bf78d059cdcca40de187a3a3ad2380f4c7e

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/ui-server/pull/94
/go github.com/kubedb/ui-server kubedb.dev/ui-server 
/pr https://github.com/kubedb/dashboard/pull/85
/go github.com/kubedb/dashboard kubedb.dev/dashboard 
/pr https://github.com/kubedb/provisioner/pull/59
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/pr https://github.com/kubedb/schema-manager/pull/85
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard c2982e934e4fb6a1ba2d9133a1bd127ef2e5f856

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server b59415fd4b042cdbc24c68c2cc7e49438afd9a3e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 7e6099e0e7b4b5bd9b5fa72eac5869274e1995dd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 893fe8d96be7341195900b46a93e970b86fe7596

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager 640fe280f0c615efabd22ecda0a85d124182eb6d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler a406fbdaa02a8349da564464e3a26067a7c22196

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/70
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server c36d61e564f10a2b328d0df81afbac93647f9229

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 45b0125690d256fe55ffb715805a8e59411a1875

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs 57ff0b52c3d7f8b5bc389ef28decadfc191c9832

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 6fc95e46445b7b245ada6031f47e61dc4e0c2bd0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 97d51c0f8241455d45d81bf1bc4da7c3d1c953c6

**Pull request merged**
