### PR TITLE
Release: v2023.01.17

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator a66421ce82048759a67ebf12902c60919c3dbabc

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/tests/pull/214
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/mongodb/pull/531
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/percona-xtradb-coordinator/pull/27
/go github.com/kubedb/percona-xtradb-coordinator kubedb.dev/percona-xtradb-coordinator 
/pr https://github.com/kubedb/elasticsearch/pull/624
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/cli/pull/695
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/mariadb-coordinator/pull/70
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/pr https://github.com/kubedb/memcached/pull/382
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/redis-coordinator/pull/60
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/pr https://github.com/kubedb/mysql/pull/519
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/replication-mode-detector/pull/222
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/mariadb/pull/196
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/pr https://github.com/kubedb/percona-xtradb/pull/297
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/redis/pull/447
/go github.com/kubedb/redis kubedb.dev/redis 
/ready-to-tag github.com/kubedb/mysql-router-init 960c85bfe3071702bb2e3d338c70be801a1d044e
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/pg-coordinator/pull/109
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/pr https://github.com/kubedb/postgres/pull/623
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/kafka/pull/12
/go github.com/kubedb/kafka kubedb.dev/kafka 
/pr https://github.com/kubedb/mysql-coordinator/pull/68
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 264d4323853580d12e0acd18aba702f23d7ea971

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka 6b49e97632ee340e4ae6ddc162b392c20fb8a054

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator 4a182b7652ecc50e3b1466840cc195cbfa4a7bcb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator 084ba8e01b7aa3836cddf1c71218efc9981d6240

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests ad9578bf6e484824e3223becfc7c094fc6de33dc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb e165db2e44a5d49180670299aca6fb7476108a32

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator d5d1f977d38d33a2d3e9b05131267d43ae966229

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 62eec8ef85c8d364265e481da4570ecea9938dc3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 35c62fa5b4755efb81d0a9b093341a6fb7e53e5e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb f8c9012716c9299d0a1d3d35f5772fb94420f3a1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 94eeb8d5b7cfda8158dee6e827b2ef3924e5eb7a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 96587959c567e23b392d0c8b231a9834632d0e04

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 2700e88dbd1fef0f7ca85efe31c8ba2b66566609

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 7b0b63f407de1c736014201fd85cf58cc5ea87c4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres d3ded3bd4b341509b1b7f5e9d3d3b662538578e5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis d4b63271e2e9cf0ee14af79eb40008894c3bfd8e

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/redis d4b63271e2e9cf0ee14af79eb40008894c3bfd8e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 6ea07cb67d9b9e0864bbd04e4ab10a5f8796e0dd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 67500f617e7361b8498252e4293138923fef1eff

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard 3d59229dbbd45b8db0439f37ab8fdc3e89fd195b

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/dashboard/pull/58
/go github.com/kubedb/dashboard kubedb.dev/dashboard 
/pr https://github.com/kubedb/provisioner/pull/35
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/pr https://github.com/kubedb/schema-manager/pull/62
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/pr https://github.com/kubedb/ui-server/pull/64
/go github.com/kubedb/ui-server kubedb.dev/ui-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 94bf0859b95c4d0beb2b4e375b7db8d48fef73d7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 6cfc446910724b799fca64c342f6b024615fa5ae

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 02cd0453bc192aff5d477501119646421af3112f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager 57e4e442a8cb98ecd8098cffb1faa1dfe42ae799

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler 4a31539ffd88838b1bfdc524557188b6415404d7

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/47
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server 7b3eff57785a842a1967a8d29bc765c38830656d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 2414928acdb179b71f3ad4138bc32f68013b7f87

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs be0e110a68cded3f9ce25d008a130d4c7dd38ea6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website cafaf3355144abe84fcf5a644eaceace13a729bc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles e19d730da737878f4a678e9f41e57351f2e32b0b

**Pull request merged**
