### PR TITLE
Release: v2024.2.14

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/db-client-go fffdeec5eb38317e6c0c2f7356b0739e7f7491d7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-restic-plugin 999bae4416986fc70c363529fc8f3ec9074ee41e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-archiver 1c0154ef43caa12250a966420b489e53038bd964

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-archiver 4e4d8ee8bfcc2c156dd2d8a86288d3084ba56f24

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-archiver ad9cbeefa4615e2de9260b05cf7371bd44784397

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/solr bfd0a91802be7f082d52a731696eaf0359799d59

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-csi-snapshotter-plugin 1af87b7417a9f9f4a4f2908a4f6397b03a34d231

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator 779d62d980f4ff7c3f9cdada3500e3a4403c677b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/zookeeper 23daf8baa95417675d47c5e1fdd92d45a85f2acb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka 8cb1975c9ed315c99f9f89fe522439693d75b5d2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 5c11f939ecc1f1744172c42f1c66e987bd488bb0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 8cecf8c54f23b1db4472ddb2b9b8b518b0ac2c5e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator c75e8445b63ac886aa268ec72f2c53c0164d10b6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb e25b687e0de99d35d433071bc14a10524ad2b563

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql e229f704658511539768c29e304d5dfbe252dfa8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/crd-manager 4c2b767329347becca1aa0f58e6866fc461660ad

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 30351cda8833f7593e0ae39fb4c7b29de2bdedc5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 7bb888269a129dbc8c179f4a390c19e3c9bb449e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 1347a8db989a014887389c0ea770b7dac173161e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch-restic-plugin 028f9ca56b68cce31f4a91b4d4110452a2b18956

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/druid 984932b23576dd18684746e973fd7fa784aeae2a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ferretdb 16eb41932b6d928218f53d89fcc4fde721149dfa

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 8442a2bca6c851b95e0c9db8f8d682446d5d6a8a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-restic-plugin cdefd8521a4c9586e39d48bd14b217ce6fce6c5a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kubedb-manifest-plugin 89311ad485b0330b5d785ce4245fff71c5302c6d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 3b3001dfbdf6290fb4ff54a4b756e035f1f61dce

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-csi-snapshotter-plugin b1c5ff1cfe3d7b7f4ec290b1393a90817b1b160b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-csi-snapshotter-plugin d08a28d2ffd468153eb323f253476c84a83bc53c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgpool c2e585ad68599f98d4defd8ca016f9446db6513f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore cb62edf398622a2f223bf2f11f93c81620e5e34b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator 08f5dded40a438fcae795db48359b216c63f887d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-restic-plugin ff7001792676912d1c31d9e6a2528c77f44ff09a

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/mongodb-restic-plugin ff7001792676912d1c31d9e6a2528c77f44ff09a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-restic-plugin 621119afa1a99a1ad47ea8464fec9dc59d4425a0
/go github.com/kubedb/redis-restic-plugin kubedb.dev/redis-restic-plugin 
/ready-to-tag github.com/kubedb/mariadb d8f0fa0c2dff63e4ad322a513510760558e25a59
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/ready-to-tag github.com/kubedb/rabbitmq 518249103c4827ab382cb2f3ca748af13350cb40
/go github.com/kubedb/rabbitmq kubedb.dev/rabbitmq 
/ready-to-tag github.com/kubedb/provider-gcp 82f52c30b26c8ab9727ee3a3d0687c59c2e5c3da
/go github.com/kubedb/provider-gcp kubedb.dev/provider-gcp 
/ready-to-tag github.com/kubedb/mysql-coordinator 850c5ca7da800684cb5498dfc444f088e2bf3e8e
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/ready-to-tag github.com/kubedb/provider-aws ec4459c4077527319d28c5d6632d5cfb60fba46d
/go github.com/kubedb/provider-aws kubedb.dev/provider-aws 
/ready-to-tag github.com/kubedb/singlestore-coordinator bd572f5d713f041424795c83d7baa44d29570106
/go github.com/kubedb/singlestore-coordinator kubedb.dev/singlestore-coordinator 
/ready-to-tag github.com/kubedb/mariadb-csi-snapshotter-plugin e19e8a61d1aa168ef38d0dd5510e838ebe27ebba
/go github.com/kubedb/mariadb-csi-snapshotter-plugin kubedb.dev/mariadb-csi-snapshotter-plugin 
/ready-to-tag github.com/kubedb/postgres 660e99f135e77f2dca4a33932515900041aab84b
/go github.com/kubedb/postgres kubedb.dev/postgres 
/ready-to-tag github.com/kubedb/provider-azure ebba4fadff65ac8325f230d5571f2fb393bf7702
/go github.com/kubedb/provider-azure kubedb.dev/provider-azure 
/ready-to-tag github.com/kubedb/mysql-router-init 6a5deed48dcf1cfda25886055976ef0879b762a1
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/tests/pull/308
/go github.com/kubedb/tests kubedb.dev/tests 
/tagged github.com/kubedb/zookeeper
/go github.com/kubedb/zookeeper kubedb.dev/zookeeper 
/tagged github.com/kubedb/ferretdb
/go github.com/kubedb/ferretdb kubedb.dev/ferretdb 
/tagged github.com/kubedb/mongodb-restic-plugin
/go github.com/kubedb/mongodb-restic-plugin kubedb.dev/mongodb-restic-plugin 
/tagged github.com/kubedb/crd-manager
/tagged github.com/kubedb/redis
/go github.com/kubedb/redis kubedb.dev/redis 
/tagged github.com/kubedb/elasticsearch-restic-plugin
/go github.com/kubedb/elasticsearch-restic-plugin kubedb.dev/elasticsearch-restic-plugin 
/tagged github.com/kubedb/druid
/go github.com/kubedb/druid kubedb.dev/druid 
/tagged github.com/kubedb/mariadb-archiver
/go github.com/kubedb/mariadb-archiver kubedb.dev/mariadb-archiver 
/tagged github.com/kubedb/solr
/go github.com/kubedb/solr kubedb.dev/solr 
/tagged github.com/kubedb/mongodb-csi-snapshotter-plugin
/go github.com/kubedb/mongodb-csi-snapshotter-plugin kubedb.dev/mongodb-csi-snapshotter-plugin 
/tagged github.com/kubedb/mongodb
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/tagged github.com/kubedb/memcached
/go github.com/kubedb/memcached kubedb.dev/memcached 
/tagged github.com/kubedb/mysql-restic-plugin
/go github.com/kubedb/mysql-restic-plugin kubedb.dev/mysql-restic-plugin 
/tagged github.com/kubedb/mysql-csi-snapshotter-plugin
/tagged github.com/kubedb/pgpool
/go github.com/kubedb/pgpool kubedb.dev/pgpool 
/tagged github.com/kubedb/pg-coordinator
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/tagged github.com/kubedb/mariadb-coordinator
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/tagged github.com/kubedb/kubedb-manifest-plugin
/go github.com/kubedb/kubedb-manifest-plugin kubedb.dev/kubedb-manifest-plugin 
/tagged github.com/kubedb/mysql-archiver
/go github.com/kubedb/mysql-archiver kubedb.dev/mysql-archiver 
/tagged github.com/kubedb/kafka
/go github.com/kubedb/kafka kubedb.dev/kafka 
/tagged github.com/kubedb/mysql
/go github.com/kubedb/mysql kubedb.dev/mysql 
/tagged github.com/kubedb/elasticsearch
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/tagged github.com/kubedb/cli
/go github.com/kubedb/cli kubedb.dev/cli 
/tagged github.com/kubedb/postgres-archiver
/go github.com/kubedb/postgres-archiver kubedb.dev/postgres-archiver 
/tagged github.com/kubedb/replication-mode-detector
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/tagged github.com/kubedb/singlestore
/go github.com/kubedb/singlestore kubedb.dev/singlestore 
/tagged github.com/kubedb/postgres-restic-plugin
/go github.com/kubedb/postgres-restic-plugin kubedb.dev/postgres-restic-plugin 
/tagged github.com/kubedb/redis-coordinator
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/tagged github.com/kubedb/percona-xtradb-coordinator
/tagged github.com/kubedb/percona-xtradb
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/tagged github.com/kubedb/postgres-csi-snapshotter-plugin
/go github.com/kubedb/postgres-csi-snapshotter-plugin kubedb.dev/postgres-csi-snapshotter-plugin

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 660e99f135e77f2dca4a33932515900041aab84b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-restic-plugin 621119afa1a99a1ad47ea8464fec9dc59d4425a0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator 850c5ca7da800684cb5498dfc444f088e2bf3e8e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/rabbitmq 518249103c4827ab382cb2f3ca748af13350cb40

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-csi-snapshotter-plugin e19e8a61d1aa168ef38d0dd5510e838ebe27ebba

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore-coordinator bd572f5d713f041424795c83d7baa44d29570106

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests 6697689212b099a5942d713ec7ab0285a2f18898

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard 50d29c4993f59e6f240a5f899ebe9c1ee51c042b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 632d6eaa9727de3e713b218c0fc04dc8f0d43ec1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql e0bbc700dcd6bbd9be07ba16c1451b5203e8e6a1

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/provisioner/pull/82
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/pr https://github.com/kubedb/schema-manager/pull/103
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/pr https://github.com/kubedb/ui-server/pull/111
/go github.com/kubedb/ui-server kubedb.dev/ui-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager b1ff9ec4c0f1d93a2dd1b32c74e9b813b195b1b2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 09fb0fd2993ba00c212a77631374f57813111350

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 31ce3b71a6840b38ae7fce9d1096165fedf2f426

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager 1a71ef8b1e82265b3b2dd05f7ab6c1d9e7b6de18

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler b5882bd532c6bd5f43a009426633cfdd9cbb9c68

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/96
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server 2de37258b9596786fac0190f5e57ea05a9ebf453

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 8505aa6d60aa386578ea546989ebb8a5efdcd98c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs 599724e702e6315bfb8f2767f1bb5a3594f3da74

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 5fa70454393ddee6a9d793b95aec79966ad863e6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles d1765084ca9c596ba496d9cd6b2c1581d4b9b070

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb d8f0fa0c2dff63e4ad322a513510760558e25a59

**Pull request merged**
