### PR TITLE
Release: v2022.02.22

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/percona-xtradb/pull/249
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/elasticsearch/pull/565
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/redis-coordinator/pull/25
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/pr https://github.com/kubedb/cli/pull/654
/go github.com/kubedb/cli kubedb.dev/cli 
/ready-to-tag github.com/kubedb/mysql-router-init 32d8ac861dd72e0d2e3da0dfac6e400dcb58eb28
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/postgres/pull/562
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/mysql/pull/455
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/mysql-coordinator/pull/29
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/pr https://github.com/kubedb/replication-mode-detector/pull/184
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/mariadb/pull/135
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/pr https://github.com/kubedb/mongodb/pull/462
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/pg-coordinator/pull/66
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/pr https://github.com/kubedb/tests/pull/169
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/mariadb-coordinator/pull/35
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/pr https://github.com/kubedb/redis/pull/386
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/memcached/pull/345
/go github.com/kubedb/memcached kubedb.dev/memcached

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli d22f9b86d5b9e63d3a12db31063942a515924094

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb d01b291464a7fb0cd5411361ec4411b32d1b3f1e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 86ec5d2a4e7819fcdbe1b3633cf1a5d0f6c1e859

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 12b89a3e73b0edfa9a40b22f961eb85c78eaa521

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch c572597382499ca2d11468ad85560fb787c37322

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests 72008dceafa9e28d063fe97785ea590d3f4f70fb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 7b764c0b9930a87ebb238a19f96166a0b8e151e6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 7a354d6c591bc9bf51c5191424aaa459874de5d6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb 6a778dd9331049152018636bd2b788c5e2740a31

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 134b2f2d201a03241e06479f55db28ed71412a34

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis f506b8ad68ae4bea39a4ae3e24b793a5f39c5799

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator 5784a320b07c0ed2d3c393036792b7cab68baf01

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator a2adbd9ca97a8b7ad1bcb2dd3a24c77895ce94a5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator c22dc23b4e079987e5fec341093722a26c60119d

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator eb50dc22be4f2b6b149ed480959d21564114e3f4

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator eb50dc22be4f2b6b149ed480959d21564114e3f4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 0bff10e8ccc1313938b6538f82875c0702f8398c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer a244100d6274fb8544cb3a6f82eb0126413aea76

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/schema-manager/pull/21
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/pr https://github.com/kubedb/ui-server/pull/25
/go github.com/kubedb/ui-server kubedb.dev/ui-server 
/pr https://github.com/kubedb/dashboard/pull/15
/go github.com/kubedb/dashboard kubedb.dev/dashboard 
/pr https://github.com/kubedb/operator/pull/456
/go github.com/kubedb/operator kubedb.dev/operator

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard dc2c5cd3891425893f458a4755b791bb05dd0db6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 27cbd85f208435ce9ef79d11814140eb4d349dd0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 62f41a7c46fab86a0685ac6ec16dc488d9b86f1c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/operator 960d2f93070d80ab658ce5a06e260ca7c4977a19

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/enterprise 9e763012a6b467471fd0bc51a14db086a2d2f72e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler 5b5cab07f1fdf9746902d337f6a01f499519dd3a

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/11
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server 70336af9ad16505f4bc73a02093e24f619935ced

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer e2136df2114f3e307d49ede3b3f1cf1495964877

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs 334e9030db0fc9892c8953ae6cf3b3c7eb122f4c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 1e01dec158ec02f55f51e2c7c9f2f7bc90d172fb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 12acb9c6d843740eea7fad3fb4ba5c3bea362b84

**Pull request merged**
