### PR TITLE
Release: v2021.01.14

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-leader-election 31050c171fcc09bf9684114892435dc95afeee27
/go github.com/kubedb/pg-leader-election kubedb.dev/pg-leader-election

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/mysql/pull/343
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/tests/pull/88
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/cli/pull/578
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/replication-mode-detector/pull/118
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/elasticsearch/pull/456
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/memcached/pull/272
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/percona-xtradb/pull/167
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/postgres/pull/456
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/mongodb/pull/354
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/redis/pull/294
/go github.com/kubedb/redis kubedb.dev/redis

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 82be6c3c9658711b8b5d270c535d0d2618f2acb3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql e5e3a121158f7afb0be1b276c354d15fefdc8f52

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector f7b0e81676b18b96fd24976dd63fe54640368d9c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 59e808c47b3b1ed97147275c5a0bd4ddce9158db

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached bdbf3281037dbd405ebae0d2251db8543493af6a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch e7304c0707029cb262a13cf62b0993c1f4e47d1b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres a53c9c67399088a474fd625b4ff5d331302cf7a2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb bb9f23208f96df40924a724fa910b8de1a5f1e20

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis b7d20a3e3be196ba04b9d25389dfceffc9a09f2d

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/tests 53972eefdbd6e88de951898f422141ccf53f6dd5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql fdd650cb2137195b02b4d9f7178849eb81a7d7e2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 693e3cee2540a937344ddb5f073e61dc97e92efa

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/operator 58a5bfd9213b3d2aaeaf509f843403295e860e04

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/kubedb-enterprise 50a3e6b97de9ed602653ac8d0da3d41c35711b60

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/kubedb-autoscaler 1eb7c3b6d0e4d200d6abe4d9b5fd5f935e9e9971

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 27d1591301df68f2c254df9c01003fcd855a1149

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs f81af71aad1580cc395c8c87a15aaaf2444ffe70

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 6f800ca03d7d248db688daf45eaf76055c940cb5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 28c24f2960b495416556f8aa9dce20901f265fe9

**Pull request merged**
