### PR TITLE
Release: v2022.10.12-rc.0

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator b1d9ecfac92f2e65b6c6d307150984df71dedcfc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests a2d4d3ac30f021f7259e8477e960143d346d2d83

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 1e715c1a9b64e78fa3b8c82350c64b8fed9a43bc

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/mysql-coordinator/pull/58
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/pr https://github.com/kubedb/elasticsearch/pull/611
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/tests/pull/200
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/cli/pull/684
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/percona-xtradb/pull/282
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/pg-coordinator/pull/99
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/pr https://github.com/kubedb/replication-mode-detector/pull/214
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/postgres/pull/605
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/mariadb-coordinator/pull/62
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/pr https://github.com/kubedb/mysql/pull/504
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/percona-xtradb-coordinator/pull/19
/go github.com/kubedb/percona-xtradb-coordinator kubedb.dev/percona-xtradb-coordinator 
/ready-to-tag github.com/kubedb/mysql-router-init e5eba9e7e02e48f52759fcbdf19007f157429238
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/redis/pull/432
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/memcached/pull/373
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/mariadb/pull/179
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/pr https://github.com/kubedb/redis-coordinator/pull/52
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/pr https://github.com/kubedb/mongodb/pull/517
/go github.com/kubedb/mongodb kubedb.dev/mongodb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres cd547a6801de33dd4149ee36e3e07a7fd47f2f76

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator cf6c54c2f78ef0b07ae52e29df3ff7d47d4f773c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 8033e31bd9329ce57d304ce89e22e30e8a932fba

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb b9e03cc5932f1af94e52b41891856d4c60b51408

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator 85fb61bbfe76ec3810570647dab8212d142c8d1a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector d051a8ebaeff7f4c2dcc952de96fc5e59ac39eca

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator 21d63eabea64c4e4c1b0e0c87bfc931734f8c35f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb b13d62cf90ffa0f9c015cbb595c1a7beaba85bda

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 030e063deb4d3f9ed96b657f4b436c8330c46691

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 24a961a88a9286ad6280e8d5430f59f2619f75df

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 8386ed4cdd1a407a25d419a44995095b5160208c

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/memcached 255abab363dd4ee724d7a495815384109e7c6d32
/ready-to-tag github.com/kubedb/mariadb-coordinator b16d49d1585b94a3891e1b47f06391dd992b3f72

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 0d58567a1fa4cd5b58ea12342f6127c610d38196

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 3dc6618f7494258b4b44baf8026db7526e7c3f37

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard fd8f1bc67b9ba68e6db2451f813ea1fab6aac07f

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/dashboard/pull/46
/go github.com/kubedb/dashboard kubedb.dev/dashboard 
/pr https://github.com/kubedb/provisioner/pull/21
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/pr https://github.com/kubedb/schema-manager/pull/51
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/pr https://github.com/kubedb/ui-server/pull/54
/go github.com/kubedb/ui-server kubedb.dev/ui-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 9dc8acb92cc1fcdc940d85ca127e1e633eece468

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 56931e130adc6f8f46b75164d96f53823f1794ca

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 5497cc1be2d4a90c31e6b803032d4fe0f8425252

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager 698d4f848eb97110adc558faff1f249a55761f71

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler 99ffb7a4b26f5043c8f3cebc68bb97fbaf1920bf

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/33
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server 1de1fe03a1578a64db43b773244d1ec591296d2c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 0d5ff889f3f98a2e150dbf3ea53291ad96386ca1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs e3682b936a289adad2c304b54d7b9579e9ab18de

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 0660caf8c30597310379243dd095ad96667ccabb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 154800a14ccee4092b5b1ef532bee10a7a5343b0

**Pull request merged**
