### PR TITLE
Release: v2022.05.24

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector fcb720f2871fea468e7417c497cbd55fe0c41b58

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch ba7dee10aca25efb544e2bdd9c5aa079ac9c3bdd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator 373a83ec090bdbeaf6d1af50ca20c68e72a5d270

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 439a9398e5cbd95e91d6131d84345b43ea3b1fb4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 85063ec7ab1f0f12e40abe7373889cf2130b98ec

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres bc3cf38ecb65662ca4d1a9b604bf3b533408cb87

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb b2fd680d2fa43b4fdc0fe779bf4a177f049d7e49

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 3dcfc3c7986d9481532288cbb13407a76dd24546

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/redis 3dcfc3c7986d9481532288cbb13407a76dd24546

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 23da6cdb731b4557cfd665a6ccc6d38febcf4681

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator fb4f029738adfd94fa9b11a85c2dca6dc0f2f23e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests 6501852d3fe284258c0139dfaa846e9526afc98e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 83f74c174b22e3568e1bb62b5178d50d1a1c685d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 988eab7691434324f5edf54b1a4a41c6a53609d7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 01318a20a3f48e89cbf00de75e7a9a38e4e5deb7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-router-init b30fd8e3c3420c8e8135c21ad87fb83a2e570909
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/ready-to-tag github.com/kubedb/mysql-coordinator 96698cb9039f2e467f51be0ded7f34aa3ded4b31
/tagged github.com/kubedb/mysql-coordinator
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/tagged github.com/kubedb/percona-xtradb
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/tagged github.com/kubedb/mongodb
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/tagged github.com/kubedb/mariadb-coordinator
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/tagged github.com/kubedb/redis-coordinator
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/tagged github.com/kubedb/pg-coordinator
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/tagged github.com/kubedb/redis
/go github.com/kubedb/redis kubedb.dev/redis 
/tagged github.com/kubedb/mysql
/go github.com/kubedb/mysql kubedb.dev/mysql 
/tagged github.com/kubedb/cli
/go github.com/kubedb/cli kubedb.dev/cli 
/tagged github.com/kubedb/elasticsearch
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/tagged github.com/kubedb/postgres
/go github.com/kubedb/postgres kubedb.dev/postgres 
/tagged github.com/kubedb/mariadb
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/tagged github.com/kubedb/replication-mode-detector
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/tagged github.com/kubedb/memcached
/go github.com/kubedb/memcached kubedb.dev/memcached 
/tagged github.com/kubedb/tests
/go github.com/kubedb/tests kubedb.dev/tests

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 283f3bf39ee58e347e14c6fb744bda109d20312d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 8bb55234a4a06ce5d25915cb82f459873f3a5d8f

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/provisioner/pull/2
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/pr https://github.com/kubedb/schema-manager/pull/29
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/pr https://github.com/kubedb/ui-server/pull/34
/go github.com/kubedb/ui-server kubedb.dev/ui-server 
/pr https://github.com/kubedb/dashboard/pull/27
/go github.com/kubedb/dashboard kubedb.dev/dashboard

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager e98aaeca0d25838b5c258b7132e942407574a8e7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 1a87a7e7b1734c5c1710390683f9b7c0b6b6b6cc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 4cb89dbdd11509d0649ab3af712b88bdb206fa71

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard 454bf6a44257fd7d72c710d9b9226f11fd553183

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager 2727742d7e65c890af06d15dba551eb2a0117a41

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler 7cb69faebfb78e3f2e223da229ccaee0c82ccc6b

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/19
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server 5d69aa6cfdad98616ff7a428ff72cb665dc18eb5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer e33921e310843355688791895c9909fa9f6b4cbc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs feacfce365f93a074205ddd3566d2a32e117f9b4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 05fa8aa2adac6dd4966607bf4c4f2eae99910e84

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 22264dc8724aa87f0d948326becc7fb24fe6df01

**Pull request merged**
