### PR TITLE
Release: v2021.01.15

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-leader-election 31050c171fcc09bf9684114892435dc95afeee27
/go github.com/kubedb/pg-leader-election kubedb.dev/pg-leader-election

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/pg-leader-election 42d7aefd54db45cd61946f4c1efbd97e967f795f
/go github.com/kubedb/pg-leader-election kubedb.dev/pg-leader-election

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/postgres/pull/457
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/cli/pull/579
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/percona-xtradb/pull/168
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/replication-mode-detector/pull/119
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/tests/pull/89
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/memcached/pull/273
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/mongodb/pull/356
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/elasticsearch/pull/457
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/mysql/pull/344
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/redis/pull/295
/go github.com/kubedb/redis kubedb.dev/redis

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 8576b8cf9b0cdacb36608dd0ad157756b3d4c962

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb bbe4cd92ecfe7fae3c4e4c8dd2e086c08eee464c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 6802d07e7817514113d1f94cf047ac7007263eb7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests 4b8b17a0004e4e82b747618ab9c795ade0cd5083

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached f066d0f39ddc9fdd115a5477bf4f2e265a50d3e0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb fd7b45bd45165bc34f2a70bc8d6a8c59c1f37e68

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector a5e82a98d203d51313897ad4e8c9e034b54882b9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 90ef17eb5befe3ac9061418a18629f40b0eeeed5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 3ed0d7091533e15cc69c18ac01d5f32cc8718820

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 3c1bf4b658f8ad7f1bec8c48ba00bdd77b1a453d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 98fd0585681ca39758c4510bfc87095fb744c976

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 9ad8e766be04b2bb150ff85c207c3dded0bcb1e1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/operator 0d1409757e2d844c7da01a76fd6db35a6d7073f7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/kubedb-enterprise 48e08e31fa247e9653eb046b7df35103692db01b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/kubedb-autoscaler 844b159ba6b6a4aa2d697cc3fcbb892da6a1b7ad

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer f8700391aac99c06d67c86e46925429d508a37d3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs d3d35a8517b08f7971277f8430d3649db45a05aa

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 2260bc7798535a0be73e7c6a573cf3290385a168

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 4dad8e0752db0dada891d37b648fc9f5aa6c6c28

**Pull request merged**
