### PR TITLE
Release: v2024.1.19-beta.1

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kubedb-manifest-plugin c77b4ae2ac94923304ca272b3709eb70fa2acfa3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-archiver e5bdae3acf9c00ff4effdd6baf0d0dc5b7e7edeb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-restic-plugin 105888a1ab92f4a23d04511e6d1f30a8a479c4d9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-restic-plugin 6ae8ae26b4daad7d23dd8ee672baf20183693f16

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-csi-snapshotter-plugin 5680265f97cc261d43e81f9bb87eb45e2ddaa3e8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-csi-snapshotter-plugin dc4f85ea91073a374a4bba83afd6b0e0bc59da01

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator fd3b211246960472e288a294594d5446f976f1dc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgpool dbb333bc8cb96450d6f09546677b7a7aa550f1ff

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator 560bc5c352c72f8edf4b998d7c01121a0fbf9452

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/druid 46c43877784d0c4ed6949f38cd03e50125a9e190

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ferretdb 68618ecb343c9e55236564942daa7e2647eaafa7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 754ba3987a341f5dc974c6c2e29c123e1ae6ac3b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb c0c58448b8b27644220d62af0387472b78aa6a51

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka 34f4967f79b64e78b070fcb54237eb812aa761ae

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-restic-plugin fac6226468687f2c5b16bb2a83c96d6c34e07409

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator 59a11671f226fd0b1f24e7ff33ea51f2c9dee178

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch-restic-plugin 584dfd93029897ba87bd824582648dedb39b46b6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-csi-snapshotter-plugin d5771cf647a34f4a06f6bacbedf3b49c2a42083b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-csi-snapshotter-plugin adac38d6625df94ad44786982f778db4a06f4485

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb c4d4942f8e9cb1827406d7e6e62806d0bbfd3a81

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-archiver e8564fe133092d3c4fc112b25cdf11a46cd0afe0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-restic-plugin 4ed2b4ae12dac8d3b0c0cca65b8a16159ddc5dea

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 44eda2d2520c41e72be23aea7852c4157925cac4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-archiver c4405c1be4fe9d24a93cf475638a16807f041457

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 026598f44ff70f7c4d39cd04d44b45e8d054cadd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 012906340f29ec1ec224e472a1514130875284ab

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql e9dbf269cdc514a7110b1bb530046232878afbb4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 72a1ee294430eae321682b176d18e3cabab37367

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests 3cfc1212e59cce00edad42ad57243bc881bb3c16

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/rabbitmq 48d2ec9592662bf47ff6ddf9318cc3f9dad98524

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 1c30e710c2b4790eba7fd79c53bee892b493b5d4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch c410b39f5b10cbd592e9c037ba6664d54f88f140

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator bc296307f8b7cedc339f73d540ede7a030c675bb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 475a5e3285b8790394c2f67c55ff1936769b058a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore 8feeb797679623edf944a6fe2966a547a9af9bfa

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector f948a65017deef5bcc175a49e47becf1bcf21fd4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/solr 58fb5b4c8da772b03e8e763d8c78a1da93f259ef

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 234b7051bbd1ba2c4e7c5445beaec0c5c6498726

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/cli 234b7051bbd1ba2c4e7c5445beaec0c5c6498726

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/cli 234b7051bbd1ba2c4e7c5445beaec0c5c6498726

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provider-aws ec4459c4077527319d28c5d6632d5cfb60fba46d
/go github.com/kubedb/provider-aws kubedb.dev/provider-aws 
/ready-to-tag github.com/kubedb/singlestore-coordinator 6440bbe1880ef7675cacaec659bec089f39b94b3
/tagged github.com/kubedb/singlestore-coordinator
/go github.com/kubedb/singlestore-coordinator kubedb.dev/singlestore-coordinator 
/ready-to-tag github.com/kubedb/provider-gcp a3de663e6f3066806d5249cea5ba8bf8a51386a2
/go github.com/kubedb/provider-gcp kubedb.dev/provider-gcp 
/ready-to-tag github.com/kubedb/provider-azure 0d449ff4b56956c72ef89a647c4df9cdea51b0cb
/go github.com/kubedb/provider-azure kubedb.dev/provider-azure 
/ready-to-tag github.com/kubedb/crd-manager 19b63054e39c2e20327fc4bf836b163fe5c9d9e5
/tagged github.com/kubedb/crd-manager
/go github.com/kubedb/crd-manager kubedb.dev/crd-manager 
/ready-to-tag github.com/kubedb/mysql-router-init 85f8c6f3b8ddc3bc057e4b704c8795ef7b479eab
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/ready-to-tag github.com/kubedb/zookeeper 28a02e01929bbf48d824071bdda344aa813586c1
/tagged github.com/kubedb/zookeeper
/go github.com/kubedb/zookeeper kubedb.dev/zookeeper 
/tagged github.com/kubedb/mysql-coordinator
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/tagged github.com/kubedb/elasticsearch-restic-plugin
/go github.com/kubedb/elasticsearch-restic-plugin kubedb.dev/elasticsearch-restic-plugin 
/tagged github.com/kubedb/mysql-archiver
/go github.com/kubedb/mysql-archiver kubedb.dev/mysql-archiver 
/tagged github.com/kubedb/mongodb-restic-plugin
/go github.com/kubedb/mongodb-restic-plugin kubedb.dev/mongodb-restic-plugin 
/tagged github.com/kubedb/mariadb-csi-snapshotter-plugin
/tagged github.com/kubedb/rabbitmq
/go github.com/kubedb/rabbitmq kubedb.dev/rabbitmq 
/tagged github.com/kubedb/replication-mode-detector
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/tagged github.com/kubedb/postgres-csi-snapshotter-plugin
/go github.com/kubedb/postgres-csi-snapshotter-plugin kubedb.dev/postgres-csi-snapshotter-plugin 
/tagged github.com/kubedb/postgres-archiver
/go github.com/kubedb/postgres-archiver kubedb.dev/postgres-archiver 
/tagged github.com/kubedb/percona-xtradb
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/tagged github.com/kubedb/pgpool
/go github.com/kubedb/pgpool kubedb.dev/pgpool 
/tagged github.com/kubedb/druid
/go github.com/kubedb/druid kubedb.dev/druid 
/tagged github.com/kubedb/postgres-restic-plugin
/go github.com/kubedb/postgres-restic-plugin kubedb.dev/postgres-restic-plugin 
/tagged github.com/kubedb/redis
/go github.com/kubedb/redis kubedb.dev/redis 
/tagged github.com/kubedb/postgres
/go github.com/kubedb/postgres kubedb.dev/postgres 
/tagged github.com/kubedb/elasticsearch
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/tagged github.com/kubedb/solr
/go github.com/kubedb/solr kubedb.dev/solr 
/tagged github.com/kubedb/cli
/go github.com/kubedb/cli kubedb.dev/cli 
/tagged github.com/kubedb/kubedb-manifest-plugin
/go github.com/kubedb/kubedb-manifest-plugin kubedb.dev/kubedb-manifest-plugin 
/tagged github.com/kubedb/mysql-restic-plugin
/go github.com/kubedb/mysql-restic-plugin kubedb.dev/mysql-restic-plugin 
/tagged github.com/kubedb/mongodb-csi-snapshotter-plugin
/go github.com/kubedb/mongodb-csi-snapshotter-plugin kubedb.dev/mongodb-csi-snapshotter-plugin 
/tagged github.com/kubedb/percona-xtradb-coordinator
/tagged github.com/kubedb/ferretdb
/go github.com/kubedb/ferretdb kubedb.dev/ferretdb 
/tagged github.com/kubedb/memcached
/go github.com/kubedb/memcached kubedb.dev/memcached 
/tagged github.com/kubedb/mariadb-archiver
/go github.com/kubedb/mariadb-archiver kubedb.dev/mariadb-archiver 
/tagged github.com/kubedb/tests
/go github.com/kubedb/tests kubedb.dev/tests 
/tagged github.com/kubedb/singlestore
/go github.com/kubedb/singlestore kubedb.dev/singlestore 
/tagged github.com/kubedb/kafka
/go github.com/kubedb/kafka kubedb.dev/kafka 
/tagged github.com/kubedb/redis-restic-plugin
/go github.com/kubedb/redis-restic-plugin kubedb.dev/redis-restic-plugin 
/tagged github.com/kubedb/mysql-csi-snapshotter-plugin
/tagged github.com/kubedb/mariadb-coordinator
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/tagged github.com/kubedb/redis-coordinator
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/tagged github.com/kubedb/mariadb
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/tagged github.com/kubedb/mysql
/go github.com/kubedb/mysql kubedb.dev/mysql 
/tagged github.com/kubedb/mongodb
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/tagged github.com/kubedb/pg-coordinator
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 55c248d5745ef501c7470c64755c5d481fde04df

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 213ebfc43fc259f4ad71ef97c163e66655ba95be

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager f14516a91b3479feb11e389a127ed0a46e03bbe2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 52cb0fa9cc129d5ac09939ed4a1f176449229dd7

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/provisioner 52cb0fa9cc129d5ac09939ed4a1f176449229dd7

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/ui-server/pull/105
/go github.com/kubedb/ui-server kubedb.dev/ui-server 
/pr https://github.com/kubedb/dashboard/pull/100
/go github.com/kubedb/dashboard kubedb.dev/dashboard 
/tagged github.com/kubedb/schema-manager
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/tagged github.com/kubedb/provisioner
/go github.com/kubedb/provisioner kubedb.dev/provisioner

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard 999f215f0be5db59207f72dc95382b8b13b385ef

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 98c1a6dd0f1306c1138af05dab76174ee9fc49f2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager 5976d8ed05f84aa30b0271eb67e657760762324b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler 7cef99b3eb1cc21fa03d4991182f3a0634034dbd

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/89
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server 2a84cedb623567275d0e6b8735debf32a50e97e6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer a58a71f15c16d76bb1f7dcdcc9e617e08d89bbcd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs 9722677b03fd58972bb22dd1405d17a7c9360d5b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 1ff427867260732ccf80bd0bd65b39408e7aa44f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 46a480e0bcd908078ad04792efb2b6f5d108cc30

**Pull request merged**
