### PR TITLE
Release: v2022.03.28

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/mariadb/pull/143
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/pr https://github.com/kubedb/mongodb/pull/469
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/ready-to-tag github.com/kubedb/mysql-router-init d4689b7ae6d41b91b178ef1bdca6b171345e1011
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/percona-xtradb/pull/255
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/ready-to-tag github.com/kubedb/tests 700325f43bc58aac1697d15e874dc6ee41ac4caa
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/elasticsearch/pull/572
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/replication-mode-detector/pull/191
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/memcached/pull/351
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/pg-coordinator/pull/72
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/pr https://github.com/kubedb/redis-coordinator/pull/29
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/pr https://github.com/kubedb/postgres/pull/567
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/mariadb-coordinator/pull/40
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/pr https://github.com/kubedb/mysql-coordinator/pull/34
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/pr https://github.com/kubedb/redis/pull/391
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/cli/pull/661
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/mysql/pull/461
/go github.com/kubedb/mysql kubedb.dev/mysql

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb 122b15e00e1af2980066e2ceaf2e30e1d03a0c55

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 9df8f77740e65d70a8f7bc09f9d7970b285f72bb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 9adf6283eaa9d7e636f6bf9c4e1d736eb8513afa

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb dfb0d0fa2d061c57cd586e02949707acd3f582ac

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 7f10dbbde0354335caabce63142692f344187256

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch f5712d4b3e09f5ae8ebac92830cf60ee8bf85352

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached c9719b95786f5913d36401fbc8eabf7556a23479

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 5d9b463ca22a8fd8d900f3727ba32d801d89cba1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 0ef8f9a4b169a41b8160053c7c911b355a8d8be2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator db28fcca09007d5b26806b88e754f8a5cdcde4fe

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator 42df94b42c82ac2c7f903ca78b4556ad4053c032

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 7463ebdeabee9caa96a94396ce65529e24a266d5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator 002fa02fd3cf77fe6a17590bb193a19064751bac

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis ad6eb9b46e7ba86538cc80780c500d834e3f9bea

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/redis ad6eb9b46e7ba86538cc80780c500d834e3f9bea

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 814d0891300bc4be170a759a659626d0c7773346

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 7ee0f89f6e69c4f3b5c999da474a49c5ccad53bc

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/operator/pull/463
/go github.com/kubedb/operator kubedb.dev/operator 
/pr https://github.com/kubedb/schema-manager/pull/27
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/pr https://github.com/kubedb/ui-server/pull/33
/go github.com/kubedb/ui-server kubedb.dev/ui-server 
/pr https://github.com/kubedb/dashboard/pull/23
/go github.com/kubedb/dashboard kubedb.dev/dashboard

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard 2835ccaeaa1e2434790607c82ecca01a4a6bb00e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 2c30ccbf0a1b894f851927326f3ca547c79a6890

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 5d16981d343c19f409c9fba36af4ee2c7ba6ecee

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/operator 93adeabfeae1f2e4e3ba2f9fa526b031a3aadb72

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/enterprise 472036101592d6f704999e5fe66c16cee44da953

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler 465b5184aa451842ce3054be0cc22fc83504910f

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/16
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server b9ed18130b63fa2f0b9eefa7c632e51868b069fd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer f0a666c67dc5615adbdc502da8edd6f5aa133957

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs 58a3b4e5fe62d16dddf103b6234edb85df2f855e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 3738b60c2fb12c338fb2cf0a1d50cd7077f37da2
/tagged github.com/kubedb/website

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 0bb0ce05a4e9a83bc08223b101ac1da542dd6d9b

**Pull request merged**
