### PR TITLE
Release: v2024.7.3-rc.0

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/db-client-go 019058482f8166ef54b1f99c9dcdf0f0e13f610b

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/mongodb/pull/637
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/singlestore-restic-plugin/pull/16
/go github.com/kubedb/singlestore-restic-plugin kubedb.dev/singlestore-restic-plugin 
/pr https://github.com/kubedb/percona-xtradb/pull/370
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/redis/pull/544
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/mysql-coordinator/pull/116
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/pr https://github.com/kubedb/dashboard-restic-plugin/pull/13
/go github.com/kubedb/dashboard-restic-plugin kubestash.dev/addon-template 
/pr https://github.com/kubedb/mariadb-csi-snapshotter-plugin/pull/24
/go github.com/kubedb/mariadb-csi-snapshotter-plugin kubedb.dev/mariadb-csi-snapshotter-plugin 
/ready-to-tag github.com/kubedb/provider-gcp 61a45eb086d91d37b389dcd437856fa9de1dd4a2
/go github.com/kubedb/provider-gcp kubedb.dev/provider-gcp 
/pr https://github.com/kubedb/mysql/pull/629
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/crd-manager/pull/34
/go github.com/kubedb/crd-manager kubedb.dev/crd-manager 
/pr https://github.com/kubedb/mariadb-coordinator/pull/120
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/pr https://github.com/kubedb/pg-coordinator/pull/167
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/pr https://github.com/kubedb/kafka/pull/96
/go github.com/kubedb/kafka kubedb.dev/kafka 
/pr https://github.com/kubedb/mssql-coordinator/pull/10
/go github.com/kubedb/mssql-coordinator kubedb.dev/mssql-coordinator 
/pr https://github.com/kubedb/mysql-csi-snapshotter-plugin/pull/22
/go github.com/kubedb/mysql-csi-snapshotter-plugin kubedb.dev/mysql-csi-snapshotter-plugin 
/pr https://github.com/kubedb/redis-coordinator/pull/106
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/pr https://github.com/kubedb/druid/pull/32
/go github.com/kubedb/druid kubedb.dev/druid 
/pr https://github.com/kubedb/mariadb-archiver/pull/21
/go github.com/kubedb/mariadb-archiver kubedb.dev/mariadb-archiver 
/pr https://github.com/kubedb/singlestore-coordinator/pull/21
/go github.com/kubedb/singlestore-coordinator kubedb.dev/singlestore-coordinator 
/pr https://github.com/kubedb/postgres-restic-plugin/pull/38
/go github.com/kubedb/postgres-restic-plugin kubedb.dev/postgres-restic-plugin 
/pr https://github.com/kubedb/replication-mode-detector/pull/272
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/mysql-restic-plugin/pull/45
/go github.com/kubedb/mysql-restic-plugin kubedb.dev/mysql-restic-plugin 
/pr https://github.com/kubedb/zookeeper-restic-plugin/pull/9
/go github.com/kubedb/zookeeper-restic-plugin kubedb.dev/zookeeper-restic-plugin 
/ready-to-tag github.com/kubedb/provider-aws 329ca2434cc87088566a985b034697eea15f584a
/go github.com/kubedb/provider-aws kubedb.dev/provider-aws 
/ready-to-tag github.com/kubedb/provider-azure 387e3f2720147ee7b0f48c2b71a4a7fcd0ada4e7
/go github.com/kubedb/provider-azure kubedb.dev/provider-azure 
/ready-to-tag github.com/kubedb/mysql-router-init f1f471e8689c159176d9b2673647581e1b0ba8a3
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/elasticsearch-restic-plugin/pull/35
/go github.com/kubedb/elasticsearch-restic-plugin kubedb.dev/elasticsearch-restic-plugin 
/pr https://github.com/kubedb/elasticsearch/pull/724
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/postgres/pull/737
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/solr/pull/35
/go github.com/kubedb/solr kubedb.dev/solr 
/pr https://github.com/kubedb/clickhouse/pull/6
/go github.com/kubedb/clickhouse kubedb.dev/clickhouse 
/pr https://github.com/kubedb/tests/pull/331
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/singlestore/pull/37
/go github.com/kubedb/singlestore kubedb.dev/singlestore 
/pr https://github.com/kubedb/mongodb-csi-snapshotter-plugin/pull/29
/go github.com/kubedb/mongodb-csi-snapshotter-plugin kubedb.dev/mongodb-csi-snapshotter-plugin 
/pr https://github.com/kubedb/percona-xtradb-coordinator/pull/75
/go github.com/kubedb/percona-xtradb-coordinator kubedb.dev/percona-xtradb-coordinator 
/pr https://github.com/kubedb/mysql-archiver/pull/35
/go github.com/kubedb/mysql-archiver kubedb.dev/mysql-archiver 
/pr https://github.com/kubedb/memcached/pull/450
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/ferretdb/pull/32
/go github.com/kubedb/ferretdb kubedb.dev/ferretdb 
/pr https://github.com/kubedb/kubedb-manifest-plugin/pull/57
/go github.com/kubedb/kubedb-manifest-plugin kubedb.dev/kubedb-manifest-plugin 
/pr https://github.com/kubedb/postgres-csi-snapshotter-plugin/pull/31
/go github.com/kubedb/postgres-csi-snapshotter-plugin kubedb.dev/postgres-csi-snapshotter-plugin 
/pr https://github.com/kubedb/pgpool/pull/37
/go github.com/kubedb/pgpool kubedb.dev/pgpool 
/pr https://github.com/kubedb/redis-restic-plugin/pull/37
/go github.com/kubedb/redis-restic-plugin kubedb.dev/redis-restic-plugin 
/pr https://github.com/kubedb/cli/pull/770
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/mssqlserver/pull/19
/go github.com/kubedb/mssqlserver kubedb.dev/mssql github.com/kubedb/mssql
/pr https://github.com/kubedb/zookeeper/pull/30
/go github.com/kubedb/zookeeper kubedb.dev/zookeeper 
/pr https://github.com/kubedb/mariadb-restic-plugin/pull/16
/go github.com/kubedb/mariadb-restic-plugin kubedb.dev/mariadb-restic-plugin 
/pr https://github.com/kubedb/postgres-archiver/pull/33
/go github.com/kubedb/postgres-archiver kubedb.dev/postgres-archiver 
/pr https://github.com/kubedb/mongodb-restic-plugin/pull/50
/go github.com/kubedb/mongodb-restic-plugin kubedb.dev/mongodb-restic-plugin 
/pr https://github.com/kubedb/mariadb/pull/272
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/pr https://github.com/kubedb/rabbitmq/pull/35
/go github.com/kubedb/rabbitmq kubedb.dev/rabbitmq

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-restic-plugin c55dd9c15b73176b093f0032445ca982561d9150

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch-restic-plugin 10c7f6907495bd628987b69ee0496a82f8b2fa01

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator e206e7ac91944f76f5174e59aacb575515967942

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-archiver 9d5d985cd80cda12245b20f86d02fbb8088c9fbe

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mssql-coordinator 56e423f5cf6c8167a24e67e9dee397aab1f90716

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-csi-snapshotter-plugin 5df0d96e93d290af7171d4ea3627cc0a0f1bb609

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator 67e20d0d126ca25495dd48f522c3886a76b7182c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-archiver b2e2904b934185c138dcc5c1a42d743e94c44f1d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/druid 8047a2d6309a11fa1a596a363dcfd25823667a9b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ferretdb c9abee7173832fdea52af8d87bc8528fe7318290

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kubedb-manifest-plugin 7a27d111db73855064e9e4084dfc5e3f270950dd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-restic-plugin cb733d7c2e539dd68ab159eb2577fd42262d7f6b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-restic-plugin 702d565887bf139b11006092c5f3c9a3061cb5a7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-csi-snapshotter-plugin 5167facbafaf9e78cb0f0ffea7b5afea7db78174

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgpool fa50af418647a15bb035e99ebcc20b36672e63c8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/zookeeper-restic-plugin 3235ccf500af230b353133a9a940b732f8f5f06d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-archiver 78bba5ae172c66a7bd8fe0a29ecdbd50dff8fbcd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore-coordinator 06e49265f222a5ca0afbe8524a0d2a627dd65739

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/zookeeper 75a1fa49c04b336a21695129aee7367d888d8a99

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-csi-snapshotter-plugin 10e977c39f66af01cf58d7d93a197d8b6fce253f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 96a43728cab529ad79ae604256f05891674e7dc8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb 63504dc0d1bd47a92bf6a2f41d07d0d09bcc44a5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/solr 38d0c5691cdc9f07df240710c5bc8466e29099dc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 30064e39076b56cb110e306297ceeaa9563256b8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 2190a3c8f5465ba1b1e0dbfcbe89563131c8ffc4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore-restic-plugin efca7ae361eac2ce58a4af24fb1e39c88083b869

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-restic-plugin 11149d995c5cfd25ff7e5306722d00bc8b6c5015

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector aa1d57196eb1e2933f803b141d0f70a80155c4a9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator b8c377fda96376378873766ca5c00baf7943335f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 824f81d9be588e574fe6068caf64b8562fabe4ba

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-csi-snapshotter-plugin cb1cfbcd765f50d9e609a55d3ed09bea34cd86b9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mssqlserver ed78c962a236ea63b25bf8ee859f5d689402debc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/clickhouse 205ad2889777a24cc704c798ecb5c3debc50fa76

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 3ca73dddaef48d5ee63158f33c24dec277328dec

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/rabbitmq ad06e69be1a74256e26b5a81443ed782f028aede

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb e65c886f85f3dcf5faddc4b7ce6b63847a6c28b4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/crd-manager 8392c6cd524f43aa327862c3d821f497a0719162

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore 7e011ab0a5632edfc3079ae38599046e423a0057

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch f3bd7f56f1660af7e708568a5a633731ff87ab3b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-restic-plugin 83efb5166c50f576ac06bac4c58c6a5563efd8a0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 3f019fadf9f94a05cb79a7c3b651e8590e4f176d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka c3f92486d4800bb8872764af0da7fb6631dc0a9a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator a26d43987f94254e6511cce689d0cdc35a28865a

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/cli b4118de70d25f3bc7bfb5c086ee3ef5f637410ab
/ready-to-tag github.com/kubedb/dashboard-restic-plugin d0c1465c3f9e36f21ee7a0e8fa24431299d664b8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer cde85494a3342c3e6173572c285c3fcd8274ffd7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 0b324506a9b3a5772c08e83bc614e8ec8eac5b5b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard cc962affa5c81f710a1c2afe9e05cfe94eac7893

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server c1d29bcb21ce11a6feeb337d8e27b9eef7af15d6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 986b36574a2332ea65eb94ecbb289975578c5cf3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager cd898070af6f158ad8776227f48b7063c92939a1

**Comment by 1gtm** [comment]
/tagged github.com/kubedb/ui-server
/go github.com/kubedb/ui-server kubedb.dev/ui-server 
/tagged github.com/kubedb/provisioner
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/tagged github.com/kubedb/schema-manager
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/112
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server d07cc3600e275194f6bb2141c1104ff7dcab8dc9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer ec8112bd30244ea00eaa87bb1e6a6273d58e0ab0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs e8021d6615424642c13445d5c78bdf24f9cb6753

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 89c973add328b6d96556f453fa978c7926cfdd0b

**Pull request merged**
