### PR TITLE
Release: v2020.11.12

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-leader-election bb6b5d6bb75db17c896bd57c2a22d567bccc785e
/go github.com/kubedb/pg-leader-election kubedb.dev/pg-leader-election

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/pg-leader-election bb6b5d6bb75db17c896bd57c2a22d567bccc785e
/go github.com/kubedb/pg-leader-election kubedb.dev/pg-leader-election

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-leader-election 2bc569cd3471b545afc2bd654b498dcd0a21a13a
/go github.com/kubedb/pg-leader-election kubedb.dev/pg-leader-election

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-leader-election 2bc569cd3471b545afc2bd654b498dcd0a21a13a
/go github.com/kubedb/pg-leader-election kubedb.dev/pg-leader-election

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/memcached/pull/245
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/percona-xtradb/pull/140
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/mysql/pull/307
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/mongodb/pull/320
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/cli/pull/551
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/elasticsearch/pull/416
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/postgres/pull/426
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/redis/pull/264
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/replication-mode-detector/pull/94
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 81e8fb7af547065496ae7c79a2b63e6b31a357f8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 00eda07f438f1d9a83f878fe81ac1aa9f7fbfdc5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 6e13a0a0ce268634ba184ca4444d9659e457d487

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 8a41db5d8240f4dc9f421a61e1844d98b7472624

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 19f17fb96e41bb553d9cff20cb34b585c1db791b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 8c0e92f0faa78898d9c2d81018db954e032e9b99

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres c83549aed2a5a16a5228bb6a6b757351b249a37b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 5d378ec3184395627b0190e1daf652df783f7789

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 27111d23ef50103676a1a9f8995951550d0b2d47

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 2c20cd82df84be9340c3d10fecf09d195fd532a2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer c04b66ab172147546c092e6636a53d5eedce084f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/operator bed5f88c35fb4331da7ebb3cfb4c53a271d24936

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/kubedb-enterprise 9aa1860e634d3890f255e2b5a23c6ae28604a520

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 41297552b8156ef2e3c8ab552f63063441618220

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs eb85e04eb2148417abbed73d1559d8c7f9b28ba8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 60a32acb7df86b0c4281815b97ce3ca1945e4f2d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles cb6f19c7466ed13644d0a5b58f6c37beba49d0e3

**Pull request merged**
