### PR TITLE
Release: v2024.8.14-rc.3

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/db-client-go b4a5b756707791e7cedc9dec9cebb650a9a141fc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-restic-plugin c1e0b54ffae6f5d28864f43b82b5de0df5548337

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-restic-plugin 5bedb88a750b04f0f7e22471809e125209528465

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch-restic-plugin e6aacd880d5b83ee50c1232f1b0e5cd98a1c25a9

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/postgres-restic-plugin/pull/44
/go github.com/kubedb/postgres-restic-plugin kubedb.dev/postgres-restic-plugin 
/pr https://github.com/kubedb/druid/pull/42
/go github.com/kubedb/druid kubedb.dev/druid 
/pr https://github.com/kubedb/elasticsearch-restic-plugin/pull/39
/go github.com/kubedb/elasticsearch-restic-plugin kubedb.dev/elasticsearch-restic-plugin 
/pr https://github.com/kubedb/mongodb-restic-plugin/pull/57
/go github.com/kubedb/mongodb-restic-plugin kubedb.dev/mongodb-restic-plugin 
/pr https://github.com/kubedb/redis-coordinator/pull/110
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/pr https://github.com/kubedb/mariadb-coordinator/pull/125
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/pr https://github.com/kubedb/mysql-coordinator/pull/121
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/pr https://github.com/kubedb/mariadb-archiver/pull/26
/go github.com/kubedb/mariadb-archiver kubedb.dev/mariadb-archiver 
/pr https://github.com/kubedb/singlestore-restic-plugin/pull/21
/go github.com/kubedb/singlestore-restic-plugin kubedb.dev/singlestore-restic-plugin 
/pr https://github.com/kubedb/mongodb/pull/647
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/mssql-coordinator/pull/14
/go github.com/kubedb/mssql-coordinator kubedb.dev/mssql-coordinator 
/pr https://github.com/kubedb/mssqlserver-archiver/pull/2
/go github.com/kubedb/mssqlserver-archiver kubedb.dev/mssqlserver-archiver 
/ready-to-tag github.com/kubedb/mysql-router-init f1f471e8689c159176d9b2673647581e1b0ba8a3
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/mariadb-restic-plugin/pull/21
/go github.com/kubedb/mariadb-restic-plugin kubedb.dev/mariadb-restic-plugin 
/pr https://github.com/kubedb/dashboard-restic-plugin/pull/17
/go github.com/kubedb/dashboard-restic-plugin kubestash.dev/addon-template 
/pr https://github.com/kubedb/kubedb-manifest-plugin/pull/63
/go github.com/kubedb/kubedb-manifest-plugin kubedb.dev/kubedb-manifest-plugin 
/pr https://github.com/kubedb/mysql-csi-snapshotter-plugin/pull/26
/go github.com/kubedb/mysql-csi-snapshotter-plugin kubedb.dev/mysql-csi-snapshotter-plugin 
/pr https://github.com/kubedb/postgres-archiver/pull/37
/go github.com/kubedb/postgres-archiver kubedb.dev/postgres-archiver 
/pr https://github.com/kubedb/percona-xtradb/pull/378
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/crd-manager/pull/44
/go github.com/kubedb/crd-manager kubedb.dev/crd-manager 
/pr https://github.com/kubedb/kafka/pull/104
/go github.com/kubedb/kafka kubedb.dev/kafka 
/pr https://github.com/kubedb/memcached/pull/462
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/pg-coordinator/pull/171
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/ready-to-tag github.com/kubedb/provider-azure 387e3f2720147ee7b0f48c2b71a4a7fcd0ada4e7
/go github.com/kubedb/provider-azure kubedb.dev/provider-azure 
/pr https://github.com/kubedb/percona-xtradb-coordinator/pull/79
/go github.com/kubedb/percona-xtradb-coordinator kubedb.dev/percona-xtradb-coordinator 
/pr https://github.com/kubedb/mysql-restic-plugin/pull/50
/go github.com/kubedb/mysql-restic-plugin kubedb.dev/mysql-restic-plugin 
/pr https://github.com/kubedb/replication-mode-detector/pull/276
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/mysql/pull/636
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/zookeeper-restic-plugin/pull/13
/go github.com/kubedb/zookeeper-restic-plugin kubedb.dev/zookeeper-restic-plugin 
/pr https://github.com/kubedb/ferretdb/pull/41
/go github.com/kubedb/ferretdb kubedb.dev/ferretdb 
/pr https://github.com/kubedb/clickhouse/pull/14
/go github.com/kubedb/clickhouse kubedb.dev/clickhouse 
/pr https://github.com/kubedb/postgres-csi-snapshotter-plugin/pull/35
/go github.com/kubedb/postgres-csi-snapshotter-plugin kubedb.dev/postgres-csi-snapshotter-plugin 
/pr https://github.com/kubedb/singlestore/pull/44
/go github.com/kubedb/singlestore kubedb.dev/singlestore 
/pr https://github.com/kubedb/tests/pull/349
/go github.com/kubedb/tests kubedb.dev/tests 
/ready-to-tag github.com/kubedb/provider-gcp 61a45eb086d91d37b389dcd437856fa9de1dd4a2
/go github.com/kubedb/provider-gcp kubedb.dev/provider-gcp 
/pr https://github.com/kubedb/mariadb-csi-snapshotter-plugin/pull/28
/go github.com/kubedb/mariadb-csi-snapshotter-plugin kubedb.dev/mariadb-csi-snapshotter-plugin 
/pr https://github.com/kubedb/singlestore-coordinator/pull/25
/go github.com/kubedb/singlestore-coordinator kubedb.dev/singlestore-coordinator 
/pr https://github.com/kubedb/solr/pull/45
/go github.com/kubedb/solr kubedb.dev/solr 
/pr https://github.com/kubedb/elasticsearch/pull/731
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/mongodb-csi-snapshotter-plugin/pull/33
/go github.com/kubedb/mongodb-csi-snapshotter-plugin kubedb.dev/mongodb-csi-snapshotter-plugin 
/pr https://github.com/kubedb/pgpool/pull/44
/go github.com/kubedb/pgpool kubedb.dev/pgpool 
/pr https://github.com/kubedb/redis/pull/555
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/redis-restic-plugin/pull/42
/go github.com/kubedb/redis-restic-plugin kubedb.dev/redis-restic-plugin 
/pr https://github.com/kubedb/mssqlserver-walg-plugin/pull/4
/go github.com/kubedb/mssqlserver-walg-plugin kubedb.dev/mssqlserver-walg-plugin 
/pr https://github.com/kubedb/zookeeper/pull/37
/go github.com/kubedb/zookeeper kubedb.dev/zookeeper 
/pr https://github.com/kubedb/postgres/pull/749
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/mysql-archiver/pull/39
/go github.com/kubedb/mysql-archiver kubedb.dev/mysql-archiver 
/pr https://github.com/kubedb/rabbitmq/pull/42
/go github.com/kubedb/rabbitmq kubedb.dev/rabbitmq 
/pr https://github.com/kubedb/mssqlserver/pull/23
/go github.com/kubedb/mssqlserver kubedb.dev/mssqlserver 
/pr https://github.com/kubedb/cli/pull/775
/go github.com/kubedb/cli kubedb.dev/cli 
/ready-to-tag github.com/kubedb/provider-aws 329ca2434cc87088566a985b034697eea15f584a
/go github.com/kubedb/provider-aws kubedb.dev/provider-aws 
/pr https://github.com/kubedb/mariadb/pull/280
/go github.com/kubedb/mariadb kubedb.dev/mariadb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore-restic-plugin 99b5c461e2444f45730aed381843a04432aa171c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator de860a65aafe55649058d594def8fe56e6c4cfc8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 53d96b8e3b72b2ebe72f4398fb20b171446e0526

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-archiver 4b3a600372d7df7e205fdb7a6890073d545e7d83

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator 486d06e4e1fe79437a27a5ba14dbe6ee326156c2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mssqlserver-archiver 7c867e64acba8c7a11580dc6ee4d5dbd2f803817

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mssql-coordinator 2bbe790a4d81e958c002ffe849d28d6633f842a8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 39e448d984f9c28c71e0b2c78d747f92a4d1b8ef

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mssqlserver 5937734af385804cb866d89548bdfd261de36c0a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-restic-plugin 21c133103d0dc4c8f7a9b4318fb875e2f9cc0a61

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard-restic-plugin 0d547b18e29c7efeabb9451eeb8a2964954231e7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kubedb-manifest-plugin 281d8891ad6bf73a0ea057c8ec6cf48f0affb79d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-restic-plugin 201ed9f470f3f06c12f6b5839b7a9929dcb1ce10

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-restic-plugin 79412f18d38a4326ee5c36dd9f397f3d36f232e4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/zookeeper-restic-plugin 0ef0eb05f1dc59ddd9f149a2eaec99f98afb9ff8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-csi-snapshotter-plugin 6136a154be5d8c9338826ed558f7dad4c7a1a49c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-archiver 60125c8e91c4e58aa7ffdd846845502b5d1682c3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/rabbitmq 9e2d1b306719b5ca5163a8087e33256c0b606681

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-archiver 2d439cb551f928b2b989aeec71a0a0362daa156b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/zookeeper 3c7a8b4d6c975838c699d414e37a685afc95c529

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/crd-manager 4fd0fdd5d52b4210d949cfd3ce3fb0e0806e18ac

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgpool 8c6ad09661b9e287ed42893dac55dc39942f724d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-csi-snapshotter-plugin 4fd050d160b97c12c3192b5df6d3ab933b18031a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/solr 5dcbfa1db160d691676e8e97091baa0ec6e74366

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore-coordinator 379e303ea1c5a8354fbcd8b65e09088616d576b2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-csi-snapshotter-plugin cdd76b1c40a4306a4da5e6d2c6910f5118258035

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 1a3ed68b87fc5ebe2aa59c1644d6588012720dbe

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator 6f7c70bc5cb7181e1c096b1b90581390fb5df222

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests 5f5d899cc6dd0c975bf7ecf71d4e65ce1b6b9bba

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator c15480fc4ba8919fd7ed3c4c664a6e039ee61aab

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore be3ac6ae56e59bf9f353f1d86ae8ed757018abb3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-csi-snapshotter-plugin 68f40d95368e8fb34c748e39e0be530b1540cd55

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/clickhouse e722214af41edb10858ac9a93a696e8e76b26079

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector fcc68baf9ae0c84da6b89d25d60394fcafd7e4b1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mssqlserver-walg-plugin 47b5046035823a958eca9c58e60ddb0c955174c0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 6e5a7875802e2258944b56674959513fde94fa8d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/druid 99fa3569136dde3a4874e1c77f774be223149126

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ferretdb 7c5d6d1ceeeb776c9e469a7a9022d2dbe40db7e1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka 61da17115d71f91fa652d52a8acca78949004900

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb 211fad7311f4348e24ebd923da6712d291137ff8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 490947fc6dd2141fffc9e120a816a70754b20d35

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 715b4713da379afdca1477f384c6babd055a484f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 43b7e2180770f12b9d0f3448d8de7a603da162a1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 3cce86fd56e420ec5256c4a65abb800e325040c2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 8e1b8b6002e716d395a92efe1ea6f6aee781ea95

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/redis 8e1b8b6002e716d395a92efe1ea6f6aee781ea95

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard 838503eba4d0f0e26d9c310d603b640d71886a9d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 6711649305a2923a6b22d91db6ef782cc0841bc4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 9820976228d218ba69636ec17c31fa811047021f

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/provisioner/pull/110
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/pr https://github.com/kubedb/schema-manager/pull/119
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/pr https://github.com/kubedb/ui-server/pull/127
/go github.com/kubedb/ui-server kubedb.dev/ui-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 717efd76c1976a45c68f783029ecf451bff65268

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 10068069a0a1174b498162f9d72a874d30ced934

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 4e8b6d9f757180855ec1b9551ae05daec755ef76

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager 483ae746e2bec5c9d439ce3302438dc6de1a862f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler 8b1eb269b9fbd4cf3b31802cdb32139f1ef71375

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/127
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server 275a209bbd10908f64dd732911e88d8fded487cd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer aefb4f7e14bc98b54847f75546cd0d0143840e12

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs e1e503d6990941ce16bc14edad71937cba0c9d68

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website c7d4406f0478a92cb3d4d30abc18d323e34d1fb0

**Pull request merged**
