### PR TITLE
Release: v2024.1.31

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/db-client-go 902c39a03fef656bba610e7b1965ac993f9d4fa2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch-restic-plugin 11a8a766f56476e21f3a4fa2ff805158e319e947

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kubedb-manifest-plugin 7d51761ccd9723ed79cf57916f83cf051282803b

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/mysql-coordinator/pull/103
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/pr https://github.com/kubedb/tests/pull/304
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/druid/pull/8
/go github.com/kubedb/druid kubedb.dev/druid 
/ready-to-tag github.com/kubedb/mysql-router-init 6a5deed48dcf1cfda25886055976ef0879b762a1
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/pg-coordinator/pull/154
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/pr https://github.com/kubedb/mariadb-csi-snapshotter-plugin/pull/11
/go github.com/kubedb/mariadb-csi-snapshotter-plugin kubedb.dev/mariadb-csi-snapshotter-plugin 
/pr https://github.com/kubedb/mongodb-csi-snapshotter-plugin/pull/15
/go github.com/kubedb/mongodb-csi-snapshotter-plugin kubedb.dev/mongodb-csi-snapshotter-plugin 
/pr https://github.com/kubedb/elasticsearch-restic-plugin/pull/19
/go github.com/kubedb/elasticsearch-restic-plugin kubedb.dev/elasticsearch-restic-plugin 
/pr https://github.com/kubedb/redis-restic-plugin/pull/20
/go github.com/kubedb/redis-restic-plugin kubedb.dev/redis-restic-plugin 
/pr https://github.com/kubedb/kubedb-manifest-plugin/pull/40
/go github.com/kubedb/kubedb-manifest-plugin kubedb.dev/kubedb-manifest-plugin 
/pr https://github.com/kubedb/pgpool/pull/12
/go github.com/kubedb/pgpool kubedb.dev/pgpool 
/pr https://github.com/kubedb/postgres-archiver/pull/21
/go github.com/kubedb/postgres-archiver kubedb.dev/postgres-archiver 
/pr https://github.com/kubedb/crd-manager/pull/13
/go github.com/kubedb/crd-manager kubedb.dev/crd-manager 
/pr https://github.com/kubedb/percona-xtradb/pull/354
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/percona-xtradb-coordinator/pull/63
/go github.com/kubedb/percona-xtradb-coordinator kubedb.dev/percona-xtradb-coordinator 
/pr https://github.com/kubedb/mysql-archiver/pull/20
/go github.com/kubedb/mysql-archiver kubedb.dev/mysql-archiver 
/pr https://github.com/kubedb/singlestore/pull/11
/go github.com/kubedb/singlestore kubedb.dev/singlestore 
/pr https://github.com/kubedb/mysql/pull/609
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/cli/pull/755
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/mysql-csi-snapshotter-plugin/pull/8
/go github.com/kubedb/mysql-csi-snapshotter-plugin kubedb.dev/mysql-csi-snapshotter-plugin 
/pr https://github.com/kubedb/elasticsearch/pull/704
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/mongodb/pull/611
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/solr/pull/12
/go github.com/kubedb/solr kubedb.dev/solr 
/pr https://github.com/kubedb/kafka/pull/76
/go github.com/kubedb/kafka kubedb.dev/kafka 
/pr https://github.com/kubedb/mariadb-coordinator/pull/107
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/pr https://github.com/kubedb/postgres-csi-snapshotter-plugin/pull/18
/go github.com/kubedb/postgres-csi-snapshotter-plugin kubedb.dev/postgres-csi-snapshotter-plugin 
/pr https://github.com/kubedb/mysql-restic-plugin/pull/24
/go github.com/kubedb/mysql-restic-plugin kubedb.dev/mysql-restic-plugin 
/pr https://github.com/kubedb/replication-mode-detector/pull/258
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/ready-to-tag github.com/kubedb/provider-aws ec4459c4077527319d28c5d6632d5cfb60fba46d
/go github.com/kubedb/provider-aws kubedb.dev/provider-aws 
/pr https://github.com/kubedb/postgres-restic-plugin/pull/17
/go github.com/kubedb/postgres-restic-plugin kubedb.dev/postgres-restic-plugin 
/ready-to-tag github.com/kubedb/provider-gcp 82f52c30b26c8ab9727ee3a3d0687c59c2e5c3da
/go github.com/kubedb/provider-gcp kubedb.dev/provider-gcp 
/pr https://github.com/kubedb/zookeeper/pull/8
/go github.com/kubedb/zookeeper kubedb.dev/zookeeper 
/pr https://github.com/kubedb/ferretdb/pull/9
/go github.com/kubedb/ferretdb kubedb.dev/ferretdb 
/pr https://github.com/kubedb/redis-coordinator/pull/94
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/ready-to-tag github.com/kubedb/provider-azure ebba4fadff65ac8325f230d5571f2fb393bf7702
/go github.com/kubedb/provider-azure kubedb.dev/provider-azure 
/pr https://github.com/kubedb/mariadb-archiver/pull/8
/go github.com/kubedb/mariadb-archiver kubedb.dev/mariadb-archiver 
/pr https://github.com/kubedb/mongodb-restic-plugin/pull/26
/go github.com/kubedb/mongodb-restic-plugin kubedb.dev/mongodb-restic-plugin 
/pr https://github.com/kubedb/postgres/pull/715
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/redis/pull/523
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/mariadb/pull/257
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/pr https://github.com/kubedb/rabbitmq/pull/9
/go github.com/kubedb/rabbitmq kubedb.dev/rabbitmq 
/pr https://github.com/kubedb/singlestore-coordinator/pull/5
/go github.com/kubedb/singlestore-coordinator kubedb.dev/singlestore-coordinator 
/pr https://github.com/kubedb/memcached/pull/423
/go github.com/kubedb/memcached kubedb.dev/memcached

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator ef84bd373f8dc73461dccad42d4cfd90344581e0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 8ff0608c5f12092281c37e7cf05103b62cc69196

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-csi-snapshotter-plugin 06a205759e7cc12d6c604e7a7324c87f4f027f49

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator 7e7d32d9961a4f65305f65ae6302ad873b02492f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests 16543a0f1a15f944d8fef2ae9e5884f74638a961

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/druid 8d4fdb69d8be680812a5bd0b9b7a9d47dc2e8b8a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgpool b6546d356f135e52d59643c53706ed496fd3f5a0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-archiver a55baa8158e73e1615140dfcd59fea056a7eecfe

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-archiver ed748c70b645de5bae12e761c0d1856669a1771a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-restic-plugin 5436cb672030051b1ce6bb05d4b1b1e3d040644e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator 6fd3b3cdb9a312457318cdc01e6616d080452317

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 279330e09a6f3511ff9659f9cb66ab661ac54d54

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-csi-snapshotter-plugin 61d40c2b3f5531806bddc2220fe2f46e8ff25aa6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore e8cf66f636d236de7a448626b57c8b0e4bf9a5a0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/solr 8be74c473a469198d0361fc8a65e5e43e72ce41d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka 8ffe42e672ae5dba81f149bea2f491baca4f7893

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/crd-manager a45ec913cd630c32871f33d7ae2d39db830b0806

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 6e2b4dee81c34c5c493cba011982110b3de33c21

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-csi-snapshotter-plugin 5e0031fc31dfdabaf97d57302bcf37dae1632922

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-restic-plugin 416d3cd668a362a851f8c7883a32ba0b5f082559

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-restic-plugin 273e6a394c18399d2a1b2a92d98b1c8b57300735

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-restic-plugin 26a2566b77dbe9d053643336930d07fbd7073a69

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres cf1b27268162773c446a290b14901c322f52461b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 4cce748f29c7503fc964b915f3a389ea697d6385

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/zookeeper 7347527ce5535d26326edce2d538ca2299490290

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator cd9b64c302491933fa9e1934ecadd627c7d4a8ba

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis bd9d152b87d88afe3d7fdebf41c43a04658c3fc6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/rabbitmq cbcc9132ceb7bf5b54beba6bf198be31613a7aa5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore-coordinator b4519449ddb3179fc3a1532d3514a1ad5f561bcd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached c43923bac0282029dcda4661df1514a507164ce2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 92691f3f0df93dacf14739ebb87c53967662235e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 3d0feb70ffddc90b57c71a2e76589d6dd8a56201

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ferretdb 19ac254de96b12885c7107049de4c422e2550706

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/mariadb bcf4484c9eb5c532eddb8d78d11a7bbe0c0edd10

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql ed8d2fcd8c1c5f473b0f5a7701540641f0c60f4d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-archiver bd6798f88aa6557ed3a91cea578af6302bebb3b6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-csi-snapshotter-plugin d28c59f90f9f4884148310f1f179a604bd00e561

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard 5ec1762e2c1d133d7925d46e50e0c1ee3316d6ba

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer f79abcddd423cefe237308bae25c64c8ba63369f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql b0d0e92cf90439cba29d55fbe6770b3750a21d4a

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/provisioner/pull/81
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/pr https://github.com/kubedb/schema-manager/pull/102
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/pr https://github.com/kubedb/ui-server/pull/110
/go github.com/kubedb/ui-server kubedb.dev/ui-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 25823133805077cd4def81bf2c880dc11ae279e4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 7a1d7c5e18c63e65c442b3e4719403b1137c49a1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 68f2737ec2badd92191d39431fb0fa440507f92f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager b97ac40dcdd84a9f449a8218ea7e32e5df21c24e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler 565129de48c4eaa73391b85da00fe6ef32b2d8b5

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/95
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server 93116fb5087dc0cf1159b069089789d7f14eae4a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 8c979fc3bb145a9e1f075e487129d810540a29cf

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs 7dd50bd8162f9b1d6c80fc0ebbf98e538b906979

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 52ad4f8774a8d131ba43d12afd1ad5de1af0c78b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 9eeca92e12a725ef2a76d1c69c3e5657a920b243

**Pull request merged**
