### PR TITLE
Release: v2021.01.02-rc.0

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-leader-election 31050c171fcc09bf9684114892435dc95afeee27
/go github.com/kubedb/pg-leader-election kubedb.dev/pg-leader-election

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/postgres/pull/452
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/cli/pull/575
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/memcached/pull/269
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/mysql/pull/337
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/percona-xtradb/pull/166
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/redis/pull/290
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/replication-mode-detector/pull/115
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/elasticsearch/pull/450
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/mongodb/pull/348
/go github.com/kubedb/mongodb kubedb.dev/mongodb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 2a3bc5a89130431606809fa967c4e7c58f186eb4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 33752041f7afe1d56e2427e53972d043ed91fd8e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 179e153afbb566f7d520c371c22cb8496eb08df7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres c7b618f5f51634f194e1f05f78cb5ce042e5e7dd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql ad9d9879177513c0e3c6766d4432488ccc9cf81f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb ee4109835ced8f0214932aaf08f742323ef58885

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis b416a016eb8ecc9a756269a797f19134c1959c5c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 9961f623575591c48556b2c680b3841d75105002

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb f545beb4148657ec7b25d16394572317e1e40153

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 51c8fee25eecf866e53561f8b4ca627c5af14a71

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 1ae8aed1e366b3aa61a9775904734e07c2a3ba1e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/operator 3ee052dcea61794922cbbccc14336710fffc1cb8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/kubedb-enterprise a9ed2e6ad11394450908073f1d1ccb0604bea9a4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/kubedb-autoscaler f346d5ef30cfb2bf93dbc8ab78741d9bc2509ccc

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/appscode/kubedb-autoscaler f346d5ef30cfb2bf93dbc8ab78741d9bc2509ccc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer feb4a3f097422dbc09e9e15036d100766fdeeb48

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs a8162bfe1bc84da35917fcffb7037bb863637af0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website fb1f6200a7f5b10e9bf7eea3866e90ba04593c19

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 5c60980c30d831fb076f55606bca634e3f70a2ab

**Pull request merged**
