### PR TITLE
Release: v2020.10.24-beta.0

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-leader-election 46c6bf57778fd1b6a3bd31b7770ce96fef4eeb4a
/go github.com/kubedb/pg-leader-election kubedb.dev/pg-leader-election

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/postgres/pull/396
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/memcached/pull/221
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/redis/pull/240
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/mysql-replication-mode-detector/pull/70
/go github.com/kubedb/mysql-replication-mode-detector kubedb.dev/mysql-replication-mode-detector 
/pr https://github.com/kubedb/elasticsearch/pull/387
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/mysql/pull/281
/go github.com/kubedb/mysql kubedb.dev/mysql 
/ready-to-tag github.com/kubedb/cli f3c43c7e711a407fbc384b903b8b9f06ebdf1444
/tagged github.com/kubedb/cli
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/mongodb/pull/289
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/percona-xtradb/pull/113
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-replication-mode-detector 557e8f762631b66e456335f6d8baff470894ebdc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 49da218cae0b77910c6942130bf8bd17ec73a6c9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres ed9a22acbeb27d8de13c9a465ce88281276d2cd1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 007e3ccd99f200964118cf3ba66c8c478aed31aa

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 14b2f1b2c7092728d2840eccccc2e63940d577cb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql da0ee5acdf5098046f03ed13d38277c4d9e70fd3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis d31b919a5b6bc742e18b32a9f6b49e130a02606d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch d6f5ae41b9861a7efdc6ca50cb3b43d9134fc8a2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql d344e43ff79ecc2d5d59914af428deda3685800c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 4c292933a90cec7864350634b386ee4b9bff9126

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/operator 2145978d4a5e702830cea4c99637fe1817b3999a

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/appscode/kubedb-enterprise d045bd2d9a5330abc02e7ef77831745b75780ff0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 051bc36a57b21c48e938384a1713beb616b4b2ab

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs 61572ebf95ae2269e3c5929f1a58d675bfde5bc4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website d3ea75ef5ac1eed5b9d4fa9752cae339a6f93b7f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 218229c10d664628794669a431220dcc2b66a238

**Pull request merged**
