### PR TITLE
Release: v2024.9.30

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/db-client-go c1fd83296798bbaf871017ce9720a41394fa5d3f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-restic-plugin 85fa28ebfd7c6de07139e7daf28bb3a28943f320

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/postgres-csi-snapshotter-plugin/pull/38
/go github.com/kubedb/postgres-csi-snapshotter-plugin kubedb.dev/postgres-csi-snapshotter-plugin 
/pr https://github.com/kubedb/kafka/pull/109
/go github.com/kubedb/kafka kubedb.dev/kafka 
/pr https://github.com/kubedb/mssqlserver/pull/30
/go github.com/kubedb/mssqlserver kubedb.dev/mssqlserver 
/pr https://github.com/kubedb/mysql/pull/642
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/elasticsearch/pull/734
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/mongodb-restic-plugin/pull/66
/go github.com/kubedb/mongodb-restic-plugin kubedb.dev/mongodb-restic-plugin 
/ready-to-tag github.com/kubedb/mssqlserver-archiver 7c04349959780da62d1e9bb6b053a68a7fed453b
/go github.com/kubedb/mssqlserver-archiver kubedb.dev/mssqlserver-archiver 
/pr https://github.com/kubedb/mysql-csi-snapshotter-plugin/pull/29
/go github.com/kubedb/mysql-csi-snapshotter-plugin kubedb.dev/mysql-csi-snapshotter-plugin 
/pr https://github.com/kubedb/clickhouse/pull/20
/go github.com/kubedb/clickhouse kubedb.dev/clickhouse 
/pr https://github.com/kubedb/zookeeper-restic-plugin/pull/17
/go github.com/kubedb/zookeeper-restic-plugin kubedb.dev/zookeeper-restic-plugin 
/pr https://github.com/kubedb/ferretdb/pull/45
/go github.com/kubedb/ferretdb kubedb.dev/ferretdb 
/pr https://github.com/kubedb/percona-xtradb-coordinator/pull/81
/go github.com/kubedb/percona-xtradb-coordinator kubedb.dev/percona-xtradb-coordinator 
/pr https://github.com/kubedb/mariadb-csi-snapshotter-plugin/pull/31
/go github.com/kubedb/mariadb-csi-snapshotter-plugin kubedb.dev/mariadb-csi-snapshotter-plugin 
/pr https://github.com/kubedb/zookeeper/pull/41
/go github.com/kubedb/zookeeper kubedb.dev/zookeeper 
/pr https://github.com/kubedb/kubedb-manifest-plugin/pull/71
/go github.com/kubedb/kubedb-manifest-plugin kubedb.dev/kubedb-manifest-plugin 
/pr https://github.com/kubedb/mariadb/pull/285
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/pr https://github.com/kubedb/mongodb-csi-snapshotter-plugin/pull/35
/go github.com/kubedb/mongodb-csi-snapshotter-plugin kubedb.dev/mongodb-csi-snapshotter-plugin 
/pr https://github.com/kubedb/redis-restic-plugin/pull/48
/go github.com/kubedb/redis-restic-plugin kubedb.dev/redis-restic-plugin 
/pr https://github.com/kubedb/postgres-archiver/pull/40
/go github.com/kubedb/postgres-archiver kubedb.dev/postgres-archiver 
/pr https://github.com/kubedb/cli/pull/778
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/mongodb/pull/658
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/singlestore-coordinator/pull/27
/go github.com/kubedb/singlestore-coordinator kubedb.dev/singlestore-coordinator 
/pr https://github.com/kubedb/elasticsearch-restic-plugin/pull/45
/go github.com/kubedb/elasticsearch-restic-plugin kubedb.dev/elasticsearch-restic-plugin 
/pr https://github.com/kubedb/mysql-archiver/pull/41
/go github.com/kubedb/mysql-archiver kubedb.dev/mysql-archiver 
/pr https://github.com/kubedb/mariadb-coordinator/pull/127
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/ready-to-tag github.com/kubedb/mysql-router-init e87d6c6ec950b5781e9f227945f2a56f514c78a6
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/rabbitmq/pull/48
/go github.com/kubedb/rabbitmq kubedb.dev/rabbitmq 
/pr https://github.com/kubedb/mysql-coordinator/pull/124
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/pr https://github.com/kubedb/replication-mode-detector/pull/278
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/ready-to-tag github.com/kubedb/provider-aws 329ca2434cc87088566a985b034697eea15f584a
/go github.com/kubedb/provider-aws kubedb.dev/provider-aws 
/pr https://github.com/kubedb/singlestore/pull/47
/go github.com/kubedb/singlestore kubedb.dev/singlestore 
/ready-to-tag github.com/kubedb/provider-gcp 61a45eb086d91d37b389dcd437856fa9de1dd4a2
/go github.com/kubedb/provider-gcp kubedb.dev/provider-gcp 
/pr https://github.com/kubedb/singlestore-restic-plugin/pull/26
/go github.com/kubedb/singlestore-restic-plugin kubedb.dev/singlestore-restic-plugin 
/pr https://github.com/kubedb/percona-xtradb/pull/381
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/solr/pull/49
/go github.com/kubedb/solr kubedb.dev/solr 
/pr https://github.com/kubedb/mariadb-archiver/pull/28
/go github.com/kubedb/mariadb-archiver kubedb.dev/mariadb-archiver 
/pr https://github.com/kubedb/postgres-restic-plugin/pull/53
/go github.com/kubedb/postgres-restic-plugin kubedb.dev/postgres-restic-plugin 
/pr https://github.com/kubedb/redis/pull/560
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/redis-coordinator/pull/112
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/pr https://github.com/kubedb/mariadb-restic-plugin/pull/26
/go github.com/kubedb/mariadb-restic-plugin kubedb.dev/mariadb-restic-plugin 
/pr https://github.com/kubedb/mysql-restic-plugin/pull/58
/go github.com/kubedb/mysql-restic-plugin kubedb.dev/mysql-restic-plugin 
/pr https://github.com/kubedb/pg-coordinator/pull/173
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/pr https://github.com/kubedb/mssql-coordinator/pull/17
/go github.com/kubedb/mssql-coordinator kubedb.dev/mssql-coordinator 
/pr https://github.com/kubedb/crd-manager/pull/50
/go github.com/kubedb/crd-manager kubedb.dev/crd-manager 
/ready-to-tag github.com/kubedb/provider-azure 387e3f2720147ee7b0f48c2b71a4a7fcd0ada4e7
/go github.com/kubedb/provider-azure kubedb.dev/provider-azure 
/pr https://github.com/kubedb/tests/pull/379
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/memcached/pull/466
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/pgpool/pull/48
/go github.com/kubedb/pgpool kubedb.dev/pgpool 
/pr https://github.com/kubedb/dashboard-restic-plugin/pull/21
/go github.com/kubedb/dashboard-restic-plugin kubestash.dev/addon-template 
/pr https://github.com/kubedb/druid/pull/50
/go github.com/kubedb/druid kubedb.dev/druid 
/pr https://github.com/kubedb/postgres/pull/754
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/mssqlserver-walg-plugin/pull/7
/go github.com/kubedb/mssqlserver-walg-plugin kubedb.dev/mssqlserver-walg-plugin

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-csi-snapshotter-plugin 0f4f4838b9e83d5e04b21deed1a522f59cb338c0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/zookeeper-restic-plugin c64eefc2bc58b70a8fc0a67a273409d018d464de

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kubedb-manifest-plugin 9e2894b56ab156c6dbba0c2fe7cbb4c2bcb495e8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-csi-snapshotter-plugin 9c987dde72f10c65a647500db4db96ee407947ff

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator 0dbbf87d7e1b4d870394664e8467cc956c978748

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql adff4b592494778d16655d489262a8a444bba14f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ferretdb 19802a3ff7cf1e59e9aaf1231b7944721177522c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-archiver 812086aae8724be9658385c55cf9125e46ec7c45

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 9a9216213f8454a0293d21c76054ffabe1476547

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/rabbitmq 4638e2981c0045d2175753f70d48c180c3034fac

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator f145403c6577153ce46360d4f29c12c6b7f7c99c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 941e7a2a363a43b83b939120fa0b9472607b1499

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore-restic-plugin 1ff32bb9276f8bbbc05dad7b238a9891c1e365b7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli 6d82a893114c96f1fd32a6c0127cc423a3a1f985

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 2a0bd464404c47178a8ee4fac22eaed71ae88ac2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-archiver 34dcc82f1e1a38667dd668874ca6fe889d2e6cc4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/solr 1e52e5c32b5ae2ab6f5aa9d9c4e30e30a029d1c6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-restic-plugin e75a130e9fccadac9b035928c06db0286565dda3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb-csi-snapshotter-plugin 94a47684a265dded42eabcf44b4f09080dda2159

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-restic-plugin 76729c2d821ba8e7b8c1abd00dd1c1b7fa4d862d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 8283bb57fbe75c7601d107acad0bf0b26e76d884

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres-archiver fac9428fe9062959d67bdc22f2a63cefec522723

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch-restic-plugin d248b0048696ed7f7d8f14671d3981676a17112b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard-restic-plugin f78d04f8def46305177b8d11ea448f1cb154e8a2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mssqlserver-walg-plugin d4fc0aa4464ed34f6c9657779420f0d72aa5b522

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres a7f61f7f60bf5c77897efbb24190c705a5a538ef

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator 1abf13d5de046632cf7acc544342851e017082b3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore-coordinator 66d0da4c3ddeee4a0d1bd3583b04100f8c91bec2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mssql-coordinator af0e9071eb1cf192db4f0814bdf1dd072885e1ee

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/crd-manager 00607da63d0de62fb8e4fbaf668540e97e44c773

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgpool 5703b7bc0907eeb6457473a551bb47476ec10185

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/zookeeper 4645156765066d3422cff6c0e0f3d2f9c4a4d7cf

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-restic-plugin ea38abbe6c4d0cd509d2c479e95cb34e077a7fe3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator c69d966ca779d6c7906e9f49d5fbfecaf4c5855d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-csi-snapshotter-plugin c9f7a01a2c44135708e86fd4d5d05f0ccc303e61

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka 9810e653c23606a8daae505d1e440d6b26a1e147

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mssqlserver 6817732896eeb7ad8c90b9b1d519529c36acdf65

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/druid 2b6a780e19448fcce0a65e0f63bc07214003a39d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/clickhouse df41f2d118e500d721ddce8c54f01261fc4b930b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cassandra 3f30b40f1358dd351ff2bd22ca752567f08bd29f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 0d0345422487d005ac83e356fda028fa13fc88a7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb bd16acf1036a19a51023906525980f5f99478c4d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/singlestore 78c83807dc0ed0d7bd41306c6c94febca2d04f9d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-restic-plugin e965823c805cacc054ccf7bf5959b4c8b9c19254

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests 2f79ea6bf54dcc8b8fb454d41b6c4d593dfbfdfb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb 8d48e934e74720106c0d58998391e894d341e03b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 9cf7cb8017e87d261908b737502bb191991f6a4c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kibana 3546f26ec7379e657bdb598040c2bb4b3d76af79

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 6398c68fc5972970ea3d6ba32fec1497d377157f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 4d644e52dd393ee294e0cbde86e51e350ff12b37

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/provisioner/pull/118
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/pr https://github.com/kubedb/schema-manager/pull/121
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/pr https://github.com/kubedb/ui-server/pull/133
/go github.com/kubedb/ui-server kubedb.dev/ui-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 53b7e0d2e917a4c1d142e9502de5dd942f32563e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager bf0555a1ffd57c7074b60b240b932a76eda18f14

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 39abc1554e73461ad42e206e71d9c3d113b3b781

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager 2a14823ccb8a3387f9521f4f161698fc3d89ae3c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler ba8c02d9be92efe005e7e9f8e6a5dc4bb00d43c4

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/132
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server 4eea505e38005997a0f5db4f932568fd0b982a12

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 1b943624a61715a39b0e5b3332876ba5b75aa11c

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/installer 1b943624a61715a39b0e5b3332876ba5b75aa11c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs c16742364b2c443fe06fd0e2464d39fbc0e4e398

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website e8705c7b37b03e99ce158a86777a7cd3381a35ca

**Pull request merged**
