### PR TITLE
Release: v2022.12.24-rc.1

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka 649dbf526f766a3424136b18a9aa976d716db93f

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/percona-xtradb-coordinator/pull/24
/go github.com/kubedb/percona-xtradb-coordinator kubedb.dev/percona-xtradb-coordinator 
/pr https://github.com/kubedb/percona-xtradb/pull/292
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/kafka/pull/8
/go github.com/kubedb/kafka kubedb.dev/kafka 
/ready-to-tag github.com/kubedb/mysql-router-init a8c367e949c94716c71d28ee045f849261917c79
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/pg-coordinator/pull/106
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/pr https://github.com/kubedb/postgres/pull/617
/go github.com/kubedb/postgres kubedb.dev/postgres 
/pr https://github.com/kubedb/tests/pull/209
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/cli/pull/690
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/mongodb/pull/526
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/mysql-coordinator/pull/65
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/pr https://github.com/kubedb/redis-coordinator/pull/57
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/pr https://github.com/kubedb/mariadb/pull/190
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/pr https://github.com/kubedb/elasticsearch/pull/619
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/mariadb-coordinator/pull/67
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/pr https://github.com/kubedb/mysql/pull/514
/go github.com/kubedb/mysql kubedb.dev/mysql 
/pr https://github.com/kubedb/replication-mode-detector/pull/219
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/memcached/pull/379
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/redis/pull/441
/go github.com/kubedb/redis kubedb.dev/redis

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator 8e83f43304844e1fd0f3647a842c97ca73b89a5f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator 24c35fcaa11b5a0845011810f1a3129d63e0f9b1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator d6df29d60c49ddc2b1b5066c506d059ab8e06097

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli f91038aa6aaf0ba4415dfad594eae59d31ae5f3c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests 436f15a7fbf47348e7a21394c4772901b61500a1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator 384700f7e72779e76c9f3cf1e8ecfbd83e1035a2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 378ac91554501eab56107900316c76f8fd61b732

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb e374cf7e400b03e694faf7cabd244758bebae3dc

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 1769f0ba5295ab9a0dd7b1b5b45797e3694cc6d5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql b2fcc9fa45a2ae164e953e61f2a11886abfc222b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb d94c3301a5454dae9f6bd76872b95ba861ab17a5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 30f4ff3ffa4770e0d7687bf48538abde88fc787e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached 0bdafbd7e642523e7a0f484810f4784618c76298

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch 0812edfeef8e301f1d9ee90063e3967a2b8a94a4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis 532ed03fb8d0ced4e6eada4c4598b9083f4bdfcf

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb 50d9424ecfb745f34ec4135d687e69ec8cca6de2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer 89675d58ba7c2fc26f7a16cbc6445f3cfd68965a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql df3d1df183fe01bd98a671552cc24ff10c6e5708

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard 0c9d9a46364c6da4a7498cb5e8adf900dd939cbb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 5734ca5e3eab80b4faec846ff66c64ceda16cdd5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 57e5c33a20066511a328a5c580cbd356df1a9aef

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/kubedb/provisioner 57e5c33a20066511a328a5c580cbd356df1a9aef

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 8254bf93fc07a3fde1f5f545c719a6fd316136a7
/go github.com/kubedb/ui-server kubedb.dev/ui-server 
/tagged github.com/kubedb/schema-manager
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/tagged github.com/kubedb/provisioner
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/tagged github.com/kubedb/dashboard
/go github.com/kubedb/dashboard kubedb.dev/dashboard

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager eab904d7a9b6637c8d8b50e06ea69fc5a5f05445

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler c941fab296f77fc4dd223d6d7b6a3fc65bf40f68

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/webhook-server/pull/42
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/webhook-server b9eabfda5671d65ef87a5546cbbb85582f7f886e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer d80dae40f70e10ecacd1c10a31a7a2db81c85b1d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs 45c86ab7a33f1fadd830db648f2aaee9d7fc3073

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 50db8e0084b2bfd21ffc90dbf6e50e3c39db8586

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles 65ece469a7d47e6d1b1955bb840f56bb27e360d2

**Pull request merged**
