### PR TITLE
Release: v2023.08.18

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/mariadb/pull/228
/go github.com/kubedb/mariadb kubedb.dev/mariadb 
/pr https://github.com/kubedb/percona-xtradb/pull/327
/go github.com/kubedb/percona-xtradb kubedb.dev/percona-xtradb 
/pr https://github.com/kubedb/percona-xtradb-coordinator/pull/46
/go github.com/kubedb/percona-xtradb-coordinator kubedb.dev/percona-xtradb-coordinator 
/pr https://github.com/kubedb/cli/pull/718
/go github.com/kubedb/cli kubedb.dev/cli 
/pr https://github.com/kubedb/replication-mode-detector/pull/241
/go github.com/kubedb/replication-mode-detector kubedb.dev/replication-mode-detector 
/pr https://github.com/kubedb/memcached/pull/402
/go github.com/kubedb/memcached kubedb.dev/memcached 
/pr https://github.com/kubedb/redis-coordinator/pull/77
/go github.com/kubedb/redis-coordinator kubedb.dev/redis-coordinator 
/pr https://github.com/kubedb/tests/pull/242
/go github.com/kubedb/tests kubedb.dev/tests 
/pr https://github.com/kubedb/elasticsearch/pull/662
/go github.com/kubedb/elasticsearch kubedb.dev/elasticsearch 
/pr https://github.com/kubedb/postgres/pull/662
/go github.com/kubedb/postgres kubedb.dev/postgres 
/ready-to-tag github.com/kubedb/mysql-router-init 2a59ae128a85a9bf4058cbe73365d6f081e0c154
/go github.com/kubedb/mysql-router-init kubedb.dev/mysql-router-init 
/pr https://github.com/kubedb/mysql-coordinator/pull/85
/go github.com/kubedb/mysql-coordinator kubedb.dev/mysql-coordinator 
/pr https://github.com/kubedb/mariadb-coordinator/pull/89
/go github.com/kubedb/mariadb-coordinator kubedb.dev/mariadb-coordinator 
/pr https://github.com/kubedb/mongodb/pull/568
/go github.com/kubedb/mongodb kubedb.dev/mongodb 
/pr https://github.com/kubedb/redis/pull/484
/go github.com/kubedb/redis kubedb.dev/redis 
/pr https://github.com/kubedb/kafka/pull/35
/go github.com/kubedb/kafka kubedb.dev/kafka 
/pr https://github.com/kubedb/pg-coordinator/pull/129
/go github.com/kubedb/pg-coordinator kubedb.dev/pg-coordinator 
/pr https://github.com/kubedb/mysql/pull/557
/go github.com/kubedb/mysql kubedb.dev/mysql

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb-coordinator 2bc9a1758766952999e225cf4e2afabb1b93573e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/tests ea935103a1024c6d597861c10815505d18ba6d5a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql-coordinator 11ad76595422b0a6b5060e6b2347e3f4d550a550

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb-coordinator 0d67bc6d570c513dea62371454b3e467a3ea61ec

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/percona-xtradb 6d522b6c1d11d143bb6ed1c4551706099b2992e2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/replication-mode-detector 11106cf6bee5317237b455e45b3d5d9b9397f351

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis-coordinator 136eb79eee77305caf0af251d7c97c2593ea9f0d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/kafka 1b83b3b312cf168bbaec3d61b28a334b6d8b42f8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mongodb df494f03b86610924f51c882b20314fb481d2e0e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/cli bbe4b2ef697a3fea83c45018c1aa89fd680b25c2

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mariadb f98e473091761c30d7e845f8f264e205fa7cddaf

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/memcached fd40e37e25fda294dd082d79cbd6d7f5347f6ec4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/postgres 8e62ebef5899092c0d89cfb230597fd7b2a8da04

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/elasticsearch bc8df6435e6c6b1bd3b982354740ecd6562b47c9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/redis ea9ebdf2ad1780604cc5aa96d7119c2eeeacc987

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/mysql 4f1a30945298050fe9f7d7d187f93ddabf43f6ac

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pg-coordinator a8ee999d5b721ea2ac72cf2bd9b2d69235835095

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/pgbouncer fe9437911968ff10c10f05641f1aa5c0daea0242

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/proxysql 8b5683490810f058fdcad83e76f6daead5fad0b9

**Comment by 1gtm** [comment]
/pr https://github.com/kubedb/dashboard/pull/81
/go github.com/kubedb/dashboard kubedb.dev/dashboard 
/pr https://github.com/kubedb/provisioner/pull/54
/go github.com/kubedb/provisioner kubedb.dev/provisioner 
/pr https://github.com/kubedb/schema-manager/pull/81
/go github.com/kubedb/schema-manager kubedb.dev/schema-manager 
/pr https://github.com/kubedb/ui-server/pull/89
/go github.com/kubedb/ui-server kubedb.dev/ui-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/dashboard 40e20d830cbe0ba383dc23e4c6f39f290218fe44

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/schema-manager 65459bc62fae360f102724dfbfe7b350592d315b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ui-server 7ccfc49c906bc6c3a573ba7e9818b3ca035d40e9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/provisioner 47f0fc823b93210d11a019a73e66c69819d8dd4c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/ops-manager 7d6c1616d35efaabcdced847a573542e0f46abf5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/autoscaler 02970fe128fd79a7647078c46367925ce0c3a2eb

**Comment by tamalsaha** [comment]
/go github.com/kubedb/webhook-server kubedb.dev/webhook-server
/ready-to-tag github.com/kubedb/webhook-server 26e9667126ce01d6815cde59854d647e1e3197ec

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/installer 6eacbd925fcd9be880e39e02acc79987c0375790

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/docs 65aa49d13d33fed3722d4cabcd6c94b47771f971

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/website 4d893f035145307c9f2fb7a44ae36ebeb9172157

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubedb/bundles c77675fa022df93841a049d0fbff6c95c1000308

**Pull request merged**
